// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AnswerPracticeData, AnswerPracticeErrors, AnswerPracticeResponses, AuditLogData, AuditLogErrors, AuditLogResponses, BankSummaryData, BankSummaryResponses, ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, CreateInviteData, CreateInviteErrors, CreateInviteResponses, InviteInfoData, InviteInfoErrors, InviteInfoResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, MeData, MeResponses, NextQuestionData, NextQuestionErrors, NextQuestionResponses, OpenInvitesData, OpenInvitesResponses, PracticeAreasData, PracticeAreasResponses, PracticeQuestionData, PracticeQuestionErrors, PracticeQuestionResponses, RegisterData, RegisterErrors, RegisterResponses, ResetData, ResetErrors, ResetInfoData, ResetInfoErrors, ResetInfoResponses, ResetLinkData, ResetLinkErrors, ResetLinkResponses, ResetResponses, RevokeInviteData, RevokeInviteErrors, RevokeInviteResponses, RevokeSessionsData, RevokeSessionsErrors, RevokeSessionsResponses, UpdateMeData, UpdateMeErrors, UpdateMeResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses, UsersData, UsersResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Invite Info
 */
export const inviteInfo = <ThrowOnError extends boolean = false>(options: Options<InviteInfoData, ThrowOnError>): RequestResult<InviteInfoResponses, InviteInfoErrors, ThrowOnError> => (options.client ?? client).post<InviteInfoResponses, InviteInfoErrors, ThrowOnError>({
    url: '/auth/invites/lookup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset Info
 */
export const resetInfo = <ThrowOnError extends boolean = false>(options: Options<ResetInfoData, ThrowOnError>): RequestResult<ResetInfoResponses, ResetInfoErrors, ThrowOnError> => (options.client ?? client).post<ResetInfoResponses, ResetInfoErrors, ThrowOnError>({
    url: '/auth/resets/lookup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset
 */
export const reset = <ThrowOnError extends boolean = false>(options: Options<ResetData, ThrowOnError>): RequestResult<ResetResponses, ResetErrors, ThrowOnError> => (options.client ?? client).post<ResetResponses, ResetErrors, ThrowOnError>({
    url: '/auth/reset',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Me
 */
export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>): RequestResult<MeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({ url: '/api/me', ...options });

/**
 * Update Me
 */
export const updateMe = <ThrowOnError extends boolean = false>(options: Options<UpdateMeData, ThrowOnError>): RequestResult<UpdateMeResponses, UpdateMeErrors, ThrowOnError> => (options.client ?? client).patch<UpdateMeResponses, UpdateMeErrors, ThrowOnError>({
    url: '/api/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change Password
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>): RequestResult<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError> => (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
    url: '/api/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Users
 */
export const users = <ThrowOnError extends boolean = false>(options?: Options<UsersData, ThrowOnError>): RequestResult<UsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<UsersResponses, unknown, ThrowOnError>({ url: '/api/admin/users', ...options });

/**
 * Update User
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> => (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    url: '/api/admin/users/{user_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset Link
 */
export const resetLink = <ThrowOnError extends boolean = false>(options: Options<ResetLinkData, ThrowOnError>): RequestResult<ResetLinkResponses, ResetLinkErrors, ThrowOnError> => (options.client ?? client).post<ResetLinkResponses, ResetLinkErrors, ThrowOnError>({ url: '/api/admin/users/{user_id}/reset-link', ...options });

/**
 * Revoke Sessions
 */
export const revokeSessions = <ThrowOnError extends boolean = false>(options: Options<RevokeSessionsData, ThrowOnError>): RequestResult<RevokeSessionsResponses, RevokeSessionsErrors, ThrowOnError> => (options.client ?? client).post<RevokeSessionsResponses, RevokeSessionsErrors, ThrowOnError>({ url: '/api/admin/users/{user_id}/revoke-sessions', ...options });

/**
 * Open Invites
 */
export const openInvites = <ThrowOnError extends boolean = false>(options?: Options<OpenInvitesData, ThrowOnError>): RequestResult<OpenInvitesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<OpenInvitesResponses, unknown, ThrowOnError>({ url: '/api/admin/invites', ...options });

/**
 * Create Invite
 */
export const createInvite = <ThrowOnError extends boolean = false>(options: Options<CreateInviteData, ThrowOnError>): RequestResult<CreateInviteResponses, CreateInviteErrors, ThrowOnError> => (options.client ?? client).post<CreateInviteResponses, CreateInviteErrors, ThrowOnError>({
    url: '/api/admin/invites',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke Invite
 */
export const revokeInvite = <ThrowOnError extends boolean = false>(options: Options<RevokeInviteData, ThrowOnError>): RequestResult<RevokeInviteResponses, RevokeInviteErrors, ThrowOnError> => (options.client ?? client).delete<RevokeInviteResponses, RevokeInviteErrors, ThrowOnError>({ url: '/api/admin/invites/{invite_id}', ...options });

/**
 * Audit Log
 */
export const auditLog = <ThrowOnError extends boolean = false>(options?: Options<AuditLogData, ThrowOnError>): RequestResult<AuditLogResponses, AuditLogErrors, ThrowOnError> => (options?.client ?? client).get<AuditLogResponses, AuditLogErrors, ThrowOnError>({ url: '/api/admin/audit', ...options });

/**
 * Bank Summary
 */
export const bankSummary = <ThrowOnError extends boolean = false>(options?: Options<BankSummaryData, ThrowOnError>): RequestResult<BankSummaryResponses, unknown, ThrowOnError> => (options?.client ?? client).get<BankSummaryResponses, unknown, ThrowOnError>({ url: '/api/admin/bank', ...options });

/**
 * Practice Areas
 */
export const practiceAreas = <ThrowOnError extends boolean = false>(options?: Options<PracticeAreasData, ThrowOnError>): RequestResult<PracticeAreasResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PracticeAreasResponses, unknown, ThrowOnError>({ url: '/api/practice/areas', ...options });

/**
 * Next Question
 */
export const nextQuestion = <ThrowOnError extends boolean = false>(options?: Options<NextQuestionData, ThrowOnError>): RequestResult<NextQuestionResponses, NextQuestionErrors, ThrowOnError> => (options?.client ?? client).get<NextQuestionResponses, NextQuestionErrors, ThrowOnError>({ url: '/api/practice/next', ...options });

/**
 * Practice Question
 */
export const practiceQuestion = <ThrowOnError extends boolean = false>(options: Options<PracticeQuestionData, ThrowOnError>): RequestResult<PracticeQuestionResponses, PracticeQuestionErrors, ThrowOnError> => (options.client ?? client).get<PracticeQuestionResponses, PracticeQuestionErrors, ThrowOnError>({ url: '/api/practice/questions/{question_id}', ...options });

/**
 * Answer Practice
 */
export const answerPractice = <ThrowOnError extends boolean = false>(options: Options<AnswerPracticeData, ThrowOnError>): RequestResult<AnswerPracticeResponses, AnswerPracticeErrors, ThrowOnError> => (options.client ?? client).post<AnswerPracticeResponses, AnswerPracticeErrors, ThrowOnError>({
    url: '/api/practice/questions/{question_id}/answer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
