// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * AdminUser
 */
export type AdminUser = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    vertical: Vertical | null;
    role: Role;
    status: Status;
    /**
     * Leaderboard Opt Out
     */
    leaderboard_opt_out: boolean;
    /**
     * Last Seen
     */
    last_seen: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Locked Until
     */
    locked_until: string | null;
};

/**
 * AnswerIn
 */
export type AnswerIn = {
    /**
     * Options
     */
    options?: Array<number> | null;
    /**
     * Value
     */
    value?: string | null;
};

/**
 * AreaProgress
 */
export type AreaProgress = {
    /**
     * Area
     */
    area: string;
    /**
     * Questions
     */
    questions: number;
    /**
     * Answered
     */
    answered: number;
    /**
     * Correct
     */
    correct: number;
    /**
     * Topics
     */
    topics: {
        [key: string]: number;
    };
};

/**
 * AuditEntry
 */
export type AuditEntry = {
    /**
     * Id
     */
    id: number;
    /**
     * At
     */
    at: string;
    /**
     * Action
     */
    action: string;
    /**
     * Actor
     */
    actor: string | null;
    /**
     * Target
     */
    target: string | null;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
};

/**
 * BankSummary
 */
export type BankSummary = {
    /**
     * Questions
     */
    questions: number;
    /**
     * Playable
     */
    playable: number;
    /**
     * Graded
     */
    graded: number;
    /**
     * By Area
     */
    by_area: {
        [key: string]: number;
    };
    /**
     * Quizzes
     */
    quizzes: number;
    /**
     * Key Changes
     */
    key_changes: number;
    /**
     * Missing Images
     */
    missing_images: number;
    /**
     * Excluded
     */
    excluded: number;
    /**
     * Imported At
     */
    imported_at: string | null;
};

/**
 * DailyArea
 */
export type DailyArea = {
    /**
     * Area
     */
    area: string;
    /**
     * Budget S
     */
    budget_s: number;
    /**
     * State
     */
    state: 'new' | 'started' | 'done';
    /**
     * Deadline At
     */
    deadline_at: string | null;
    /**
     * Correct
     */
    correct: boolean | null;
    /**
     * Late
     */
    late: boolean | null;
    /**
     * Points
     */
    points: number;
};

/**
 * DailyResult
 */
export type DailyResult = {
    question: PlayQuestion;
    feedback: Feedback;
    /**
     * Late
     */
    late: boolean;
    /**
     * Points
     */
    points: number;
    /**
     * Streak
     */
    streak: number;
};

/**
 * DailyStatus
 */
export type DailyStatus = {
    /**
     * Day
     */
    day: string;
    /**
     * Streak
     */
    streak: number;
    /**
     * Points Today
     */
    points_today: number;
    /**
     * Areas
     */
    areas: Array<DailyArea>;
};

/**
 * Feedback
 *
 * What the player sees after answering: the official answer and any worked solution.
 */
export type Feedback = {
    /**
     * Correct
     */
    correct: boolean | null;
    /**
     * Official
     */
    official: string | null;
    /**
     * Correct Options
     */
    correct_options: Array<number>;
    /**
     * Solutions
     */
    solutions: Array<SolutionOut>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InviteIn
 */
export type InviteIn = {
    role?: Role;
    vertical?: Vertical | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * InviteInfo
 */
export type InviteInfo = {
    role: Role;
    vertical: Vertical | null;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * LeaderRow
 */
export type LeaderRow = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Display Name
     */
    display_name: string;
    vertical: Vertical | null;
    /**
     * Points
     */
    points: number;
    /**
     * Me
     */
    me: boolean;
};

/**
 * Leaderboard
 */
export type Leaderboard = {
    /**
     * Period
     */
    period: 'season' | 'week';
    /**
     * Board
     */
    board: 'everyone' | 'mech' | 'elec' | 'rules';
    /**
     * Rows
     */
    rows: Array<LeaderRow>;
    /**
     * Null until the member scores in this period
     */
    me: MyRank | null;
    /**
     * Players
     *
     * People on this board, including any beyond the rows shown
     */
    players: number;
};

/**
 * Link
 */
export type Link = {
    /**
     * Url
     */
    url: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * LoginIn
 */
export type LoginIn = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Me
 */
export type Me = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    vertical: Vertical | null;
    role: Role;
    /**
     * Leaderboard Opt Out
     */
    leaderboard_opt_out: boolean;
};

/**
 * MockAnswerIn
 */
export type MockAnswerIn = {
    /**
     * Options
     */
    options?: Array<number> | null;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Attempt Id
     */
    attempt_id: number;
};

/**
 * MockItem
 */
export type MockItem = {
    question: PlayQuestion;
    feedback: Feedback;
    /**
     * Late
     */
    late: boolean;
};

/**
 * MockQuiz
 */
export type MockQuiz = {
    /**
     * Id
     */
    id: number;
    /**
     * Label
     */
    label: string;
    /**
     * Year
     */
    year: number;
    /**
     * Vehicle Class
     */
    vehicle_class: string;
    /**
     * Held On
     */
    held_on: string | null;
    /**
     * Questions
     */
    questions: number;
    /**
     * Graded
     */
    graded: number;
    /**
     * Total Time S
     */
    total_time_s: number | null;
    /**
     * Bar To Beat
     */
    bar_to_beat: string | null;
    /**
     * Best
     *
     * Most correct answers in a finished run
     */
    best: number | null;
    /**
     * Open Session
     */
    open_session: number | null;
};

/**
 * MockState
 */
export type MockState = {
    /**
     * Session Id
     */
    session_id: number;
    /**
     * Quiz Id
     */
    quiz_id: number;
    /**
     * Label
     */
    label: string;
    /**
     * Position
     *
     * Questions already answered
     */
    position: number;
    /**
     * Total
     */
    total: number;
    current: TimedQuestion | null;
    summary: MockSummary | null;
};

/**
 * MockSummary
 */
export type MockSummary = {
    /**
     * Correct
     */
    correct: number;
    /**
     * Graded
     */
    graded: number;
    /**
     * Points
     */
    points: number;
    /**
     * Counted
     */
    counted: boolean;
    /**
     * Bar To Beat
     */
    bar_to_beat: string | null;
    /**
     * Items
     */
    items: Array<MockItem>;
};

/**
 * MyRank
 *
 * The requesting member's own place, shown even when they are hidden or outside the top rows.
 */
export type MyRank = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Points
     */
    points: number;
    /**
     * Hidden
     *
     * Opted out: others don't see them on the board
     */
    hidden: boolean;
};

/**
 * OpenInvite
 */
export type OpenInvite = {
    /**
     * Id
     */
    id: number;
    role: Role;
    vertical: Vertical | null;
    /**
     * Note
     */
    note: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * Option
 */
export type Option = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
};

/**
 * PasswordChangeIn
 */
export type PasswordChangeIn = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PlayQuestion
 *
 * A question before it is answered: nothing here may reveal the answer.
 */
export type PlayQuestion = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
    /**
     * Answer Kind
     */
    answer_kind: string;
    /**
     * Graded
     */
    graded: boolean;
    /**
     * Values
     *
     * How many values a list answer needs, when known
     */
    values: number | null;
    /**
     * Time S
     */
    time_s: number | null;
    /**
     * Area
     */
    area: string;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Images
     */
    images: Array<string>;
    /**
     * Options
     */
    options: Array<Option>;
    /**
     * Quizzes
     */
    quizzes: Array<string>;
};

/**
 * ProfileIn
 */
export type ProfileIn = {
    /**
     * Display Name
     */
    display_name?: string | null;
    vertical?: Vertical | null;
    /**
     * Leaderboard Opt Out
     */
    leaderboard_opt_out?: boolean | null;
};

/**
 * RegisterIn
 */
export type RegisterIn = {
    /**
     * Token
     */
    token: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Password
     */
    password: string;
    vertical?: Vertical | null;
};

/**
 * ReportIn
 */
export type ReportIn = {
    /**
     * Message
     */
    message: string;
};

/**
 * ResetIn
 */
export type ResetIn = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ResetInfo
 */
export type ResetInfo = {
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * ReviewOption
 */
export type ReviewOption = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
    /**
     * Official
     */
    official: boolean;
    /**
     * Corrected
     */
    corrected: boolean;
};

/**
 * ReviewPage
 */
export type ReviewPage = {
    /**
     * Rows
     */
    rows: Array<ReviewRow>;
    /**
     * Total
     */
    total: number;
    /**
     * Queues
     */
    queues: {
        [key: string]: number;
    };
};

/**
 * ReviewPatch
 */
export type ReviewPatch = {
    /**
     * Area
     */
    area?: 'mech' | 'elec' | 'rules' | 'unclassified' | null;
    /**
     * Topic
     */
    topic?: string | null;
    /**
     * Labels Reviewed
     */
    labels_reviewed?: boolean | null;
    /**
     * Excluded
     */
    excluded?: boolean | null;
    /**
     * Exclusion Note
     */
    exclusion_note?: string | null;
    /**
     * Acknowledge Change
     */
    acknowledge_change?: boolean | null;
};

/**
 * ReviewQuestion
 *
 * Everything a reviewer needs about one question, answers included (reviewers only).
 */
export type ReviewQuestion = {
    /**
     * Id
     */
    id: number;
    /**
     * Fsquiz Id
     */
    fsquiz_id: number | null;
    /**
     * Type
     */
    type: string;
    /**
     * Text
     */
    text: string;
    /**
     * Images
     */
    images: Array<string>;
    /**
     * Area
     */
    area: string;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Labels Reviewed
     */
    labels_reviewed: boolean;
    /**
     * Answer Kind
     */
    answer_kind: string;
    /**
     * Graded
     */
    graded: boolean;
    /**
     * Playable
     */
    playable: boolean;
    /**
     * Images Missing
     */
    images_missing: boolean;
    /**
     * Excluded
     */
    excluded: boolean;
    /**
     * Exclusion Note
     */
    exclusion_note: string | null;
    /**
     * Key Changed At
     */
    key_changed_at: string | null;
    /**
     * Official
     */
    official: string | null;
    /**
     * Correction
     */
    correction: string | null;
    /**
     * Options
     */
    options: Array<ReviewOption>;
    /**
     * Quizzes
     */
    quizzes: Array<string>;
    /**
     * Reports
     */
    reports: Array<ReviewReport>;
    /**
     * Answered
     */
    answered: number;
    /**
     * Right
     */
    right: number;
    /**
     * Answer Hidden
     *
     * The reviewer's own live question: answers withheld until answered
     */
    answer_hidden: boolean;
};

/**
 * ReviewReport
 */
export type ReviewReport = {
    /**
     * Id
     */
    id: number;
    /**
     * By
     */
    by: string | null;
    /**
     * Message
     */
    message: string;
    /**
     * At
     */
    at: string;
};

/**
 * ReviewRow
 */
export type ReviewRow = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
    /**
     * Area
     */
    area: string;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Answer Kind
     */
    answer_kind: string;
    /**
     * Graded
     */
    graded: boolean;
    /**
     * Playable
     */
    playable: boolean;
    /**
     * Excluded
     */
    excluded: boolean;
    /**
     * Labels Reviewed
     */
    labels_reviewed: boolean;
    /**
     * Key Changed At
     */
    key_changed_at: string | null;
    /**
     * Reports
     */
    reports: number;
};

/**
 * Role
 */
export const Role = {
    MEMBER: 'member',
    REVIEWER: 'reviewer',
    ADMIN: 'admin'
} as const;

/**
 * Role
 */
export type Role = typeof Role[keyof typeof Role];

/**
 * SolutionOut
 */
export type SolutionOut = {
    /**
     * Text
     */
    text: string | null;
    /**
     * Images
     */
    images: Array<string>;
};

/**
 * Status
 */
export const Status = {
    ACTIVE: 'active',
    ALUMNI: 'alumni',
    DISABLED: 'disabled'
} as const;

/**
 * Status
 */
export type Status = typeof Status[keyof typeof Status];

/**
 * TimedQuestion
 *
 * A question whose clock is running. `server_now` lets the browser correct for its own clock.
 */
export type TimedQuestion = {
    /**
     * Attempt Id
     */
    attempt_id: number;
    question: PlayQuestion;
    /**
     * Deadline At
     */
    deadline_at: string;
    /**
     * Server Now
     */
    server_now: string;
};

/**
 * TokenIn
 */
export type TokenIn = {
    /**
     * Token
     */
    token: string;
};

/**
 * UserPatch
 */
export type UserPatch = {
    role?: Role | null;
    status?: Status | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Vertical
 */
export const Vertical = {
    MANAGEMENT: 'Management',
    MECHANICAL: 'Mechanical',
    TRACTIVE_SYSTEM: 'Tractive System',
    ELECTRONICS: 'Electronics',
    DRIVERLESS: 'Driverless',
    BUSINESS: 'Business',
    BOARD: 'Board'
} as const;

/**
 * Vertical
 */
export type Vertical = typeof Vertical[keyof typeof Vertical];

/**
 * VerticalBoard
 */
export type VerticalBoard = {
    /**
     * Period
     */
    period: 'season' | 'week';
    /**
     * Rows
     */
    rows: Array<VerticalRow>;
};

/**
 * VerticalRow
 */
export type VerticalRow = {
    vertical: Vertical;
    /**
     * Members
     */
    members: number;
    /**
     * Points Per Member
     */
    points_per_member: number;
    /**
     * Participation
     *
     * Share of members who answered a daily question in the last 7 days
     */
    participation: number;
};

export type LoginData = {
    body: LoginIn;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type InviteInfoData = {
    body: TokenIn;
    path?: never;
    query?: never;
    url: '/auth/invites/lookup';
};

export type InviteInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteInfoError = InviteInfoErrors[keyof InviteInfoErrors];

export type InviteInfoResponses = {
    /**
     * Successful Response
     */
    200: InviteInfo;
};

export type InviteInfoResponse = InviteInfoResponses[keyof InviteInfoResponses];

export type RegisterData = {
    body: RegisterIn;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: Me;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type ResetInfoData = {
    body: TokenIn;
    path?: never;
    query?: never;
    url: '/auth/resets/lookup';
};

export type ResetInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetInfoError = ResetInfoErrors[keyof ResetInfoErrors];

export type ResetInfoResponses = {
    /**
     * Successful Response
     */
    200: ResetInfo;
};

export type ResetInfoResponse = ResetInfoResponses[keyof ResetInfoResponses];

export type ResetData = {
    body: ResetIn;
    path?: never;
    query?: never;
    url: '/auth/reset';
};

export type ResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetError = ResetErrors[keyof ResetErrors];

export type ResetResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResetResponse = ResetResponses[keyof ResetResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type UpdateMeData = {
    body: ProfileIn;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type UpdateMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type ChangePasswordData = {
    body: PasswordChangeIn;
    path?: never;
    query?: never;
    url: '/api/me/password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type UsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/users';
};

export type UsersResponses = {
    /**
     * Response Users
     *
     * Successful Response
     */
    200: Array<AdminUser>;
};

export type UsersResponse = UsersResponses[keyof UsersResponses];

export type UpdateUserData = {
    body: UserPatch;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: AdminUser;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ResetLinkData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}/reset-link';
};

export type ResetLinkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetLinkError = ResetLinkErrors[keyof ResetLinkErrors];

export type ResetLinkResponses = {
    /**
     * Successful Response
     */
    201: Link;
};

export type ResetLinkResponse = ResetLinkResponses[keyof ResetLinkResponses];

export type RevokeSessionsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}/revoke-sessions';
};

export type RevokeSessionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeSessionsError = RevokeSessionsErrors[keyof RevokeSessionsErrors];

export type RevokeSessionsResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeSessionsResponse = RevokeSessionsResponses[keyof RevokeSessionsResponses];

export type OpenInvitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/invites';
};

export type OpenInvitesResponses = {
    /**
     * Response Open Invites
     *
     * Successful Response
     */
    200: Array<OpenInvite>;
};

export type OpenInvitesResponse = OpenInvitesResponses[keyof OpenInvitesResponses];

export type CreateInviteData = {
    body: InviteIn;
    path?: never;
    query?: never;
    url: '/api/admin/invites';
};

export type CreateInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInviteError = CreateInviteErrors[keyof CreateInviteErrors];

export type CreateInviteResponses = {
    /**
     * Successful Response
     */
    201: Link;
};

export type CreateInviteResponse = CreateInviteResponses[keyof CreateInviteResponses];

export type RevokeInviteData = {
    body?: never;
    path: {
        /**
         * Invite Id
         */
        invite_id: number;
    };
    query?: never;
    url: '/api/admin/invites/{invite_id}';
};

export type RevokeInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeInviteError = RevokeInviteErrors[keyof RevokeInviteErrors];

export type RevokeInviteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeInviteResponse = RevokeInviteResponses[keyof RevokeInviteResponses];

export type AuditLogData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/admin/audit';
};

export type AuditLogErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuditLogError = AuditLogErrors[keyof AuditLogErrors];

export type AuditLogResponses = {
    /**
     * Response Audit Log
     *
     * Successful Response
     */
    200: Array<AuditEntry>;
};

export type AuditLogResponse = AuditLogResponses[keyof AuditLogResponses];

export type BankSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/bank';
};

export type BankSummaryResponses = {
    /**
     * Successful Response
     */
    200: BankSummary;
};

export type BankSummaryResponse = BankSummaryResponses[keyof BankSummaryResponses];

export type PracticeAreasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/practice/areas';
};

export type PracticeAreasResponses = {
    /**
     * Response Practice Areas
     *
     * Successful Response
     */
    200: Array<AreaProgress>;
};

export type PracticeAreasResponse = PracticeAreasResponses[keyof PracticeAreasResponses];

export type NextQuestionData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Area
         */
        area?: 'mech' | 'elec' | 'rules' | 'unclassified' | null;
        /**
         * Topic
         */
        topic?: string | null;
        /**
         * Skip
         */
        skip?: number | null;
    };
    url: '/api/practice/next';
};

export type NextQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NextQuestionError = NextQuestionErrors[keyof NextQuestionErrors];

export type NextQuestionResponses = {
    /**
     * Successful Response
     */
    200: PlayQuestion;
};

export type NextQuestionResponse = NextQuestionResponses[keyof NextQuestionResponses];

export type PracticeQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/practice/questions/{question_id}';
};

export type PracticeQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PracticeQuestionError = PracticeQuestionErrors[keyof PracticeQuestionErrors];

export type PracticeQuestionResponses = {
    /**
     * Successful Response
     */
    200: PlayQuestion;
};

export type PracticeQuestionResponse = PracticeQuestionResponses[keyof PracticeQuestionResponses];

export type AnswerPracticeData = {
    body: AnswerIn;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/practice/questions/{question_id}/answer';
};

export type AnswerPracticeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerPracticeError = AnswerPracticeErrors[keyof AnswerPracticeErrors];

export type AnswerPracticeResponses = {
    /**
     * Successful Response
     */
    200: Feedback;
};

export type AnswerPracticeResponse = AnswerPracticeResponses[keyof AnswerPracticeResponses];

export type DailyStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/daily';
};

export type DailyStatusResponses = {
    /**
     * Successful Response
     */
    200: DailyStatus;
};

export type DailyStatusResponse = DailyStatusResponses[keyof DailyStatusResponses];

export type StartDailyData = {
    body?: never;
    path: {
        /**
         * Area
         */
        area: 'mech' | 'elec' | 'rules';
    };
    query?: never;
    url: '/api/daily/{area}/start';
};

export type StartDailyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartDailyError = StartDailyErrors[keyof StartDailyErrors];

export type StartDailyResponses = {
    /**
     * Successful Response
     */
    200: TimedQuestion;
};

export type StartDailyResponse = StartDailyResponses[keyof StartDailyResponses];

export type AnswerDailyData = {
    body: AnswerIn;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: number;
    };
    query?: never;
    url: '/api/daily/attempts/{attempt_id}/answer';
};

export type AnswerDailyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerDailyError = AnswerDailyErrors[keyof AnswerDailyErrors];

export type AnswerDailyResponses = {
    /**
     * Successful Response
     */
    200: DailyResult;
};

export type AnswerDailyResponse = AnswerDailyResponses[keyof AnswerDailyResponses];

export type ReviewDailyData = {
    body?: never;
    path: {
        /**
         * Area
         */
        area: 'mech' | 'elec' | 'rules';
    };
    query?: never;
    url: '/api/daily/{area}/review';
};

export type ReviewDailyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewDailyError = ReviewDailyErrors[keyof ReviewDailyErrors];

export type ReviewDailyResponses = {
    /**
     * Successful Response
     */
    200: DailyResult;
};

export type ReviewDailyResponse = ReviewDailyResponses[keyof ReviewDailyResponses];

export type MockQuizzesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mock/quizzes';
};

export type MockQuizzesResponses = {
    /**
     * Response Mock Quizzes
     *
     * Successful Response
     */
    200: Array<MockQuiz>;
};

export type MockQuizzesResponse = MockQuizzesResponses[keyof MockQuizzesResponses];

export type StartMockData = {
    body?: never;
    path: {
        /**
         * Quiz Id
         */
        quiz_id: number;
    };
    query?: never;
    url: '/api/mock/quizzes/{quiz_id}/start';
};

export type StartMockErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartMockError = StartMockErrors[keyof StartMockErrors];

export type StartMockResponses = {
    /**
     * Successful Response
     */
    200: MockState;
};

export type StartMockResponse = StartMockResponses[keyof StartMockResponses];

export type MockStateData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: number;
    };
    query?: never;
    url: '/api/mock/sessions/{session_id}';
};

export type MockStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MockStateError = MockStateErrors[keyof MockStateErrors];

export type MockStateResponses = {
    /**
     * Successful Response
     */
    200: MockState;
};

export type MockStateResponse = MockStateResponses[keyof MockStateResponses];

export type AnswerMockData = {
    body: MockAnswerIn;
    path: {
        /**
         * Session Id
         */
        session_id: number;
    };
    query?: never;
    url: '/api/mock/sessions/{session_id}/answer';
};

export type AnswerMockErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerMockError = AnswerMockErrors[keyof AnswerMockErrors];

export type AnswerMockResponses = {
    /**
     * Successful Response
     */
    200: MockState;
};

export type AnswerMockResponse = AnswerMockResponses[keyof AnswerMockResponses];

export type ReviewQuestionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Queue
         */
        queue?: 'all' | 'reports' | 'changed' | 'unclassified' | 'ungraded' | 'excluded';
        /**
         * Area
         */
        area?: 'mech' | 'elec' | 'rules' | 'unclassified' | null;
        /**
         * Topic
         */
        topic?: string | null;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/review/questions';
};

export type ReviewQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewQuestionsError = ReviewQuestionsErrors[keyof ReviewQuestionsErrors];

export type ReviewQuestionsResponses = {
    /**
     * Successful Response
     */
    200: ReviewPage;
};

export type ReviewQuestionsResponse = ReviewQuestionsResponses[keyof ReviewQuestionsResponses];

export type ReviewQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/review/questions/{question_id}';
};

export type ReviewQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewQuestionError = ReviewQuestionErrors[keyof ReviewQuestionErrors];

export type ReviewQuestionResponses = {
    /**
     * Successful Response
     */
    200: ReviewQuestion;
};

export type ReviewQuestionResponse = ReviewQuestionResponses[keyof ReviewQuestionResponses];

export type UpdateQuestionData = {
    body: ReviewPatch;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/review/questions/{question_id}';
};

export type UpdateQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateQuestionError = UpdateQuestionErrors[keyof UpdateQuestionErrors];

export type UpdateQuestionResponses = {
    /**
     * Successful Response
     */
    200: ReviewQuestion;
};

export type UpdateQuestionResponse = UpdateQuestionResponses[keyof UpdateQuestionResponses];

export type RemoveCorrectionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/review/questions/{question_id}/answer';
};

export type RemoveCorrectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveCorrectionError = RemoveCorrectionErrors[keyof RemoveCorrectionErrors];

export type RemoveCorrectionResponses = {
    /**
     * Successful Response
     */
    200: ReviewQuestion;
};

export type RemoveCorrectionResponse = RemoveCorrectionResponses[keyof RemoveCorrectionResponses];

export type CorrectAnswerData = {
    body: AnswerIn;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/review/questions/{question_id}/answer';
};

export type CorrectAnswerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CorrectAnswerError = CorrectAnswerErrors[keyof CorrectAnswerErrors];

export type CorrectAnswerResponses = {
    /**
     * Successful Response
     */
    200: ReviewQuestion;
};

export type CorrectAnswerResponse = CorrectAnswerResponses[keyof CorrectAnswerResponses];

export type ResolveReportData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: number;
    };
    query?: never;
    url: '/api/review/reports/{report_id}/resolve';
};

export type ResolveReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveReportError = ResolveReportErrors[keyof ResolveReportErrors];

export type ResolveReportResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResolveReportResponse = ResolveReportResponses[keyof ResolveReportResponses];

export type ReportQuestionData = {
    body: ReportIn;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/questions/{question_id}/report';
};

export type ReportQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportQuestionError = ReportQuestionErrors[keyof ReportQuestionErrors];

export type ReportQuestionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ReportQuestionResponse = ReportQuestionResponses[keyof ReportQuestionResponses];

export type GetLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Board
         */
        board?: 'everyone' | 'mech' | 'elec' | 'rules';
        /**
         * Period
         */
        period?: 'season' | 'week';
    };
    url: '/api/leaderboard';
};

export type GetLeaderboardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLeaderboardError = GetLeaderboardErrors[keyof GetLeaderboardErrors];

export type GetLeaderboardResponses = {
    /**
     * Successful Response
     */
    200: Leaderboard;
};

export type GetLeaderboardResponse = GetLeaderboardResponses[keyof GetLeaderboardResponses];

export type VerticalLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Period
         */
        period?: 'season' | 'week';
    };
    url: '/api/leaderboard/verticals';
};

export type VerticalLeaderboardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerticalLeaderboardError = VerticalLeaderboardErrors[keyof VerticalLeaderboardErrors];

export type VerticalLeaderboardResponses = {
    /**
     * Successful Response
     */
    200: VerticalBoard;
};

export type VerticalLeaderboardResponse = VerticalLeaderboardResponses[keyof VerticalLeaderboardResponses];
