// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * AdminUser
 */
export type AdminUser = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    vertical: Vertical | null;
    role: Role;
    status: Status;
    /**
     * Leaderboard Opt Out
     */
    leaderboard_opt_out: boolean;
    /**
     * Last Seen
     */
    last_seen: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Locked Until
     */
    locked_until: string | null;
};

/**
 * AuditEntry
 */
export type AuditEntry = {
    /**
     * Id
     */
    id: number;
    /**
     * At
     */
    at: string;
    /**
     * Action
     */
    action: string;
    /**
     * Actor
     */
    actor: string | null;
    /**
     * Target
     */
    target: string | null;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
};

/**
 * BankSummary
 */
export type BankSummary = {
    /**
     * Questions
     */
    questions: number;
    /**
     * Playable
     */
    playable: number;
    /**
     * Graded
     */
    graded: number;
    /**
     * By Area
     */
    by_area: {
        [key: string]: number;
    };
    /**
     * Quizzes
     */
    quizzes: number;
    /**
     * Key Changes
     */
    key_changes: number;
    /**
     * Imported At
     */
    imported_at: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InviteIn
 */
export type InviteIn = {
    role?: Role;
    vertical?: Vertical | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * InviteInfo
 */
export type InviteInfo = {
    role: Role;
    vertical: Vertical | null;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * Link
 */
export type Link = {
    /**
     * Url
     */
    url: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * LoginIn
 */
export type LoginIn = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Me
 */
export type Me = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    vertical: Vertical | null;
    role: Role;
    /**
     * Leaderboard Opt Out
     */
    leaderboard_opt_out: boolean;
};

/**
 * OpenInvite
 */
export type OpenInvite = {
    /**
     * Id
     */
    id: number;
    role: Role;
    vertical: Vertical | null;
    /**
     * Note
     */
    note: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * PasswordChangeIn
 */
export type PasswordChangeIn = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ProfileIn
 */
export type ProfileIn = {
    /**
     * Display Name
     */
    display_name?: string | null;
    vertical?: Vertical | null;
    /**
     * Leaderboard Opt Out
     */
    leaderboard_opt_out?: boolean | null;
};

/**
 * RegisterIn
 */
export type RegisterIn = {
    /**
     * Token
     */
    token: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Password
     */
    password: string;
    vertical?: Vertical | null;
};

/**
 * ResetIn
 */
export type ResetIn = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ResetInfo
 */
export type ResetInfo = {
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * Role
 */
export const Role = {
    MEMBER: 'member',
    REVIEWER: 'reviewer',
    ADMIN: 'admin'
} as const;

/**
 * Role
 */
export type Role = typeof Role[keyof typeof Role];

/**
 * Status
 */
export const Status = {
    ACTIVE: 'active',
    ALUMNI: 'alumni',
    DISABLED: 'disabled'
} as const;

/**
 * Status
 */
export type Status = typeof Status[keyof typeof Status];

/**
 * TokenIn
 */
export type TokenIn = {
    /**
     * Token
     */
    token: string;
};

/**
 * UserPatch
 */
export type UserPatch = {
    role?: Role | null;
    status?: Status | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Vertical
 */
export const Vertical = {
    MANAGEMENT: 'Management',
    MECHANICAL: 'Mechanical',
    TRACTIVE_SYSTEM: 'Tractive System',
    ELECTRONICS: 'Electronics',
    DRIVERLESS: 'Driverless',
    BUSINESS: 'Business',
    BOARD: 'Board'
} as const;

/**
 * Vertical
 */
export type Vertical = typeof Vertical[keyof typeof Vertical];

export type LoginData = {
    body: LoginIn;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type InviteInfoData = {
    body: TokenIn;
    path?: never;
    query?: never;
    url: '/auth/invites/lookup';
};

export type InviteInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteInfoError = InviteInfoErrors[keyof InviteInfoErrors];

export type InviteInfoResponses = {
    /**
     * Successful Response
     */
    200: InviteInfo;
};

export type InviteInfoResponse = InviteInfoResponses[keyof InviteInfoResponses];

export type RegisterData = {
    body: RegisterIn;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: Me;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type ResetInfoData = {
    body: TokenIn;
    path?: never;
    query?: never;
    url: '/auth/resets/lookup';
};

export type ResetInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetInfoError = ResetInfoErrors[keyof ResetInfoErrors];

export type ResetInfoResponses = {
    /**
     * Successful Response
     */
    200: ResetInfo;
};

export type ResetInfoResponse = ResetInfoResponses[keyof ResetInfoResponses];

export type ResetData = {
    body: ResetIn;
    path?: never;
    query?: never;
    url: '/auth/reset';
};

export type ResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetError = ResetErrors[keyof ResetErrors];

export type ResetResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResetResponse = ResetResponses[keyof ResetResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type UpdateMeData = {
    body: ProfileIn;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type UpdateMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type ChangePasswordData = {
    body: PasswordChangeIn;
    path?: never;
    query?: never;
    url: '/api/me/password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type UsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/users';
};

export type UsersResponses = {
    /**
     * Response Users
     *
     * Successful Response
     */
    200: Array<AdminUser>;
};

export type UsersResponse = UsersResponses[keyof UsersResponses];

export type UpdateUserData = {
    body: UserPatch;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: AdminUser;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ResetLinkData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}/reset-link';
};

export type ResetLinkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetLinkError = ResetLinkErrors[keyof ResetLinkErrors];

export type ResetLinkResponses = {
    /**
     * Successful Response
     */
    201: Link;
};

export type ResetLinkResponse = ResetLinkResponses[keyof ResetLinkResponses];

export type RevokeSessionsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}/revoke-sessions';
};

export type RevokeSessionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeSessionsError = RevokeSessionsErrors[keyof RevokeSessionsErrors];

export type RevokeSessionsResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeSessionsResponse = RevokeSessionsResponses[keyof RevokeSessionsResponses];

export type OpenInvitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/invites';
};

export type OpenInvitesResponses = {
    /**
     * Response Open Invites
     *
     * Successful Response
     */
    200: Array<OpenInvite>;
};

export type OpenInvitesResponse = OpenInvitesResponses[keyof OpenInvitesResponses];

export type CreateInviteData = {
    body: InviteIn;
    path?: never;
    query?: never;
    url: '/api/admin/invites';
};

export type CreateInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInviteError = CreateInviteErrors[keyof CreateInviteErrors];

export type CreateInviteResponses = {
    /**
     * Successful Response
     */
    201: Link;
};

export type CreateInviteResponse = CreateInviteResponses[keyof CreateInviteResponses];

export type RevokeInviteData = {
    body?: never;
    path: {
        /**
         * Invite Id
         */
        invite_id: number;
    };
    query?: never;
    url: '/api/admin/invites/{invite_id}';
};

export type RevokeInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeInviteError = RevokeInviteErrors[keyof RevokeInviteErrors];

export type RevokeInviteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeInviteResponse = RevokeInviteResponses[keyof RevokeInviteResponses];

export type AuditLogData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/admin/audit';
};

export type AuditLogErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuditLogError = AuditLogErrors[keyof AuditLogErrors];

export type AuditLogResponses = {
    /**
     * Response Audit Log
     *
     * Successful Response
     */
    200: Array<AuditEntry>;
};

export type AuditLogResponse = AuditLogResponses[keyof AuditLogResponses];

export type BankSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/bank';
};

export type BankSummaryResponses = {
    /**
     * Successful Response
     */
    200: BankSummary;
};

export type BankSummaryResponse = BankSummaryResponses[keyof BankSummaryResponses];
