// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * AccountOut
 *
 * The account level: XP from every answer, it only goes up.
 */
export type AccountOut = {
    /**
     * Level
     */
    level: number;
    /**
     * Xp
     */
    xp: number;
    /**
     * Into
     *
     * XP into the current level
     */
    into: number;
    /**
     * Needed
     *
     * XP the current level needs
     */
    needed: number;
    /**
     * Next Milestone
     *
     * The next level with an emblem frame
     */
    next_milestone: number | null;
    /**
     * Combo
     *
     * Right answers in a row
     */
    combo: number;
    /**
     * First Wins Left
     *
     * Right answers left today with the first-win bonus
     */
    first_wins_left: number;
    /**
     * Streak
     */
    streak: number;
    /**
     * Streak Bonus
     *
     * Extra XP on right answers from the daily streak, in percent
     */
    streak_bonus: number;
    /**
     * Streak Freezes
     *
     * Freezes held: each saves the streak on a missed day
     */
    streak_freezes: number;
    /**
     * Rested Xp
     *
     * Rested XP banked while away: it doubles XP until spent
     */
    rested_xp: number;
};

/**
 * AdminUser
 */
export type AdminUser = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    vertical: Vertical | null;
    role: Role;
    status: Status;
    position: Position;
    /**
     * Xp
     */
    xp: number;
    /**
     * Rank Points
     */
    rank_points: number;
    /**
     * Rank By Position
     *
     * Their rank points if moved to each position: shown before a change is saved
     */
    rank_by_position: {
        [key in Position]?: number;
    };
    /**
     * Leaderboard Opt Out
     */
    leaderboard_opt_out: boolean;
    /**
     * Last Seen
     */
    last_seen: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Locked Until
     */
    locked_until: string | null;
    /**
     * Left At
     *
     * Alumni or disabled since; the account is deleted a year later
     */
    left_at: string | null;
};

/**
 * AdvanceIn
 *
 * The step the host's screen showed, so a double tap can't skip one.
 */
export type AdvanceIn = {
    /**
     * State
     */
    state: 'lobby' | 'open' | 'closed';
    /**
     * Position
     */
    position: number;
};

/**
 * Aids
 */
export type Aids = {
    /**
     * Formulas
     */
    formulas: boolean;
    /**
     * Learn More
     */
    learn_more: boolean;
    /**
     * Hint
     */
    hint: boolean;
};

/**
 * AlumniIn
 */
export type AlumniIn = {
    /**
     * User Ids
     */
    user_ids: Array<number>;
};

/**
 * AlumniOut
 */
export type AlumniOut = {
    /**
     * Marked
     */
    marked: number;
};

/**
 * AnswerIn
 */
export type AnswerIn = {
    /**
     * Options
     */
    options?: Array<number> | null;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Unsure
     *
     * "I'm not sure": no answer; the official one shown for half a wrong answer's LP
     */
    unsure?: boolean;
};

/**
 * AreaProgress
 */
export type AreaProgress = {
    /**
     * Area
     */
    area: string;
    /**
     * Questions
     */
    questions: number;
    /**
     * Answered
     */
    answered: number;
    /**
     * Correct
     */
    correct: number;
    /**
     * Topics
     */
    topics: {
        [key: string]: number;
    };
};

/**
 * AuditEntry
 */
export type AuditEntry = {
    /**
     * Id
     */
    id: number;
    /**
     * At
     */
    at: string;
    /**
     * Action
     */
    action: string;
    /**
     * Actor
     */
    actor: string | null;
    /**
     * Target
     */
    target: string | null;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
};

/**
 * BankSummary
 */
export type BankSummary = {
    /**
     * Questions
     */
    questions: number;
    /**
     * Playable
     */
    playable: number;
    /**
     * Graded
     */
    graded: number;
    /**
     * By Area
     */
    by_area: {
        [key: string]: number;
    };
    /**
     * Quizzes
     */
    quizzes: number;
    /**
     * Key Changes
     */
    key_changes: number;
    /**
     * Missing Images
     */
    missing_images: number;
    /**
     * Excluded
     */
    excluded: number;
    /**
     * Imported At
     */
    imported_at: string | null;
};

/**
 * DailyArea
 */
export type DailyArea = {
    /**
     * Area
     */
    area: string;
    /**
     * Budget S
     */
    budget_s: number;
    /**
     * State
     */
    state: 'new' | 'started' | 'done';
    /**
     * Deadline At
     */
    deadline_at: string | null;
    /**
     * Correct
     */
    correct: boolean | null;
    /**
     * Late
     */
    late: boolean | null;
    /**
     * Passed
     *
     * Answered "I'm not sure"
     */
    passed?: boolean;
    /**
     * Xp
     */
    xp: number;
    /**
     * Lp
     */
    lp: number;
};

/**
 * DailyResult
 */
export type DailyResult = {
    question: PlayQuestion;
    feedback: Feedback;
    /**
     * What you sent
     */
    answer?: KeyIn | null;
    /**
     * Late
     */
    late: boolean;
    /**
     * Xp
     */
    xp: number;
    /**
     * Lp
     */
    lp: number;
    /**
     * Streak
     */
    streak: number;
};

/**
 * DailyStatus
 */
export type DailyStatus = {
    /**
     * Day
     */
    day: string;
    /**
     * Streak
     */
    streak: number;
    /**
     * Xp Today
     */
    xp_today: number;
    /**
     * Lp Today
     */
    lp_today: number;
    /**
     * Areas
     */
    areas: Array<DailyArea>;
};

/**
 * DeleteAccountIn
 */
export type DeleteAccountIn = {
    /**
     * Password
     */
    password: string;
};

/**
 * DocLink
 */
export type DocLink = {
    /**
     * Title
     */
    title: string;
    /**
     * Type
     *
     * As FS-Quiz names it: Rulebook, Handbook, Additional Rules...
     */
    type: string;
    /**
     * Year
     */
    year: number;
    /**
     * Url
     *
     * The PDF on doc.fs-quiz.eu
     */
    url: string;
};

/**
 * Export
 *
 * Everything MingoQuiz stores about the member who asks (GET /api/me/export).
 */
export type Export = {
    /**
     * Exported At
     */
    exported_at: string;
    account: ExportAccount;
    invite: ExportInvite | null;
    /**
     * Pending Hints
     */
    pending_hints: Array<number>;
    /**
     * Answers
     */
    answers: Array<ExportAnswer>;
    /**
     * Mock Runs
     */
    mock_runs: Array<ExportMockRun>;
    live: ExportLive;
    /**
     * Reports
     */
    reports: Array<ExportReport>;
    /**
     * Streak Freezes Used
     */
    streak_freezes_used: Array<string>;
    /**
     * Password Resets
     */
    password_resets: Array<ExportReset>;
    /**
     * Sign Ins
     */
    sign_ins: Array<ExportSignIn>;
    /**
     * Account History
     */
    account_history: Array<ExportHistory>;
    /**
     * Actions
     */
    actions: Array<ExportAction>;
};

/**
 * ExportAccount
 */
export type ExportAccount = {
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Vertical
     */
    vertical: string | null;
    /**
     * Subdepartments
     */
    subdepartments: Array<string>;
    /**
     * Position
     */
    position: string;
    /**
     * Role
     */
    role: string;
    /**
     * Status
     */
    status: string;
    /**
     * Xp
     */
    xp: number;
    /**
     * Xp Before Ranked
     *
     * Lifetime XP from before ranks and account levels (ADR 0007)
     */
    xp_before_ranked: number;
    /**
     * Rank Points
     */
    rank_points: number;
    /**
     * Rank Season
     *
     * The season the rank points belong to; 0 if never placed
     */
    rank_season: number;
    /**
     * Best Division
     *
     * The highest division reached in that season
     */
    best_division: string;
    /**
     * Position Lifts
     *
     * The LP each raise of position gave this season, which a lower position takes back
     */
    position_lifts: {
        [key: string]: number | number;
    } | null;
    /**
     * Right In A Row
     */
    right_in_a_row: number;
    /**
     * Wrong In A Row
     */
    wrong_in_a_row: number;
    /**
     * Rested Xp
     */
    rested_xp: number;
    /**
     * Rested On
     */
    rested_on: string | null;
    /**
     * Streak Freezes
     */
    streak_freezes: number;
    /**
     * Streak Freeze Earned On
     */
    streak_freeze_earned_on: string | null;
    /**
     * Hidden From Leaderboard
     */
    hidden_from_leaderboard: boolean;
    /**
     * Joined At
     */
    joined_at: string;
    /**
     * Last Seen
     */
    last_seen: string | null;
    /**
     * Failed Sign Ins
     */
    failed_sign_ins: number;
    /**
     * Locked Until
     */
    locked_until: string | null;
    /**
     * Inactive Since
     *
     * Alumni or disabled since
     */
    inactive_since: string | null;
    /**
     * Deleted On
     *
     * When the account will be deleted, if inactive
     */
    deleted_on: string | null;
};

/**
 * ExportAction
 */
export type ExportAction = {
    /**
     * At
     */
    at: string;
    /**
     * Action
     */
    action: string;
    /**
     * On
     */
    on: string;
};

/**
 * ExportAnswer
 */
export type ExportAnswer = {
    /**
     * Question Id
     */
    question_id: number;
    /**
     * Question
     */
    question: string;
    /**
     * Mode
     */
    mode: string;
    /**
     * Area
     */
    area: string | null;
    /**
     * Answer
     */
    answer: {
        [key: string]: unknown;
    };
    /**
     * Correct
     *
     * Hidden (null) while a mock run or live quiz is still going
     */
    correct: boolean | null;
    /**
     * Passed
     */
    passed: boolean;
    /**
     * Hint Used
     */
    hint_used: boolean;
    /**
     * Xp
     */
    xp: number;
    /**
     * Lp
     */
    lp: number;
    /**
     * Late
     */
    late: boolean | null;
    /**
     * Day
     */
    day: string | null;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Submitted At
     */
    submitted_at: string | null;
};

/**
 * ExportHistory
 */
export type ExportHistory = {
    /**
     * At
     */
    at: string;
    /**
     * Action
     */
    action: string;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
};

/**
 * ExportHosted
 */
export type ExportHosted = {
    /**
     * Code
     */
    code: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * ExportInvite
 */
export type ExportInvite = {
    /**
     * Role
     */
    role: string;
    /**
     * Vertical
     */
    vertical: string | null;
    /**
     * Note
     */
    note: string | null;
    /**
     * Used At
     */
    used_at: string | null;
};

/**
 * ExportLive
 */
export type ExportLive = {
    /**
     * Joined
     */
    joined: Array<ExportLiveJoin>;
    /**
     * Hosted
     */
    hosted: Array<ExportHosted>;
    /**
     * Answers Sent As Captain
     */
    answers_sent_as_captain: Array<ExportLiveAnswer>;
    /**
     * Proposals
     */
    proposals: Array<ExportProposal>;
};

/**
 * ExportLiveAnswer
 */
export type ExportLiveAnswer = {
    /**
     * Code
     */
    code: string;
    /**
     * Question
     */
    question: number;
    /**
     * Answer
     */
    answer: {
        [key: string]: unknown;
    };
    /**
     * Correct
     */
    correct: boolean | null;
    /**
     * Submitted At
     */
    submitted_at: string;
};

/**
 * ExportLiveJoin
 */
export type ExportLiveJoin = {
    /**
     * Code
     */
    code: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Joined At
     */
    joined_at: string;
    /**
     * Removed By Host
     */
    removed_by_host: boolean;
    /**
     * Table
     */
    table: string | null;
    /**
     * Captain
     */
    captain: boolean;
};

/**
 * ExportMockRun
 */
export type ExportMockRun = {
    /**
     * Quiz Id
     */
    quiz_id: number;
    /**
     * Season
     */
    season: number;
    /**
     * Counted
     */
    counted: boolean;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * ExportProposal
 */
export type ExportProposal = {
    /**
     * Code
     */
    code: string;
    /**
     * Question
     */
    question: number;
    /**
     * Answer
     */
    answer: {
        [key: string]: unknown;
    };
    /**
     * At
     */
    at: string;
};

/**
 * ExportReport
 */
export type ExportReport = {
    /**
     * Question Id
     */
    question_id: number;
    /**
     * Message
     */
    message: string;
    /**
     * At
     */
    at: string;
    /**
     * Handled At
     */
    handled_at: string | null;
};

/**
 * ExportReset
 */
export type ExportReset = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Used At
     */
    used_at: string | null;
};

/**
 * ExportSignIn
 */
export type ExportSignIn = {
    /**
     * Started At
     */
    started_at: string;
    /**
     * Last Seen
     */
    last_seen: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * Feedback
 *
 * What the player sees after answering: the official answer and any worked solution.
 */
export type Feedback = {
    /**
     * Correct
     */
    correct: boolean | null;
    /**
     * Official
     */
    official: string | null;
    /**
     * Correct Options
     */
    correct_options: Array<number>;
    /**
     * Solutions
     */
    solutions: Array<SolutionOut>;
    /**
     * Xp
     *
     * XP this answer earned
     */
    xp?: number;
    /**
     * Lp
     *
     * LP it won or lost
     */
    lp?: number;
    /**
     * Bonuses
     *
     * XP bonuses: first_win, combo, streak, crit
     */
    bonuses?: {
        [key: string]: number;
    };
    /**
     * Combo
     *
     * Right answers in a row, this one included
     */
    combo?: number;
    /**
     * Comeback
     *
     * A right answer after a bad run: 1.5x LP
     */
    comeback?: boolean;
    /**
     * Cushioned
     *
     * A loss halved by the bad run
     */
    cushioned?: boolean;
    /**
     * Promoted
     *
     * Into a division not reached before this season
     */
    promoted?: boolean;
    /**
     * Rose
     *
     * Back up into a division reached before
     */
    rose?: boolean;
    /**
     * Demoted
     */
    demoted?: boolean;
    /**
     * Rank Points
     *
     * Rank points after this answer
     */
    rank_points?: number | null;
    /**
     * Level
     *
     * Account level after this answer
     */
    level?: number | null;
    /**
     * Level Up
     *
     * This answer took the account to a new level
     */
    level_up?: boolean;
    /**
     * Passed
     *
     * The player said "I'm not sure"
     */
    passed?: boolean;
};

/**
 * Formula
 */
export type Formula = {
    /**
     * Name
     */
    name: string;
    /**
     * Formula
     */
    formula: string;
    /**
     * Where
     */
    where?: string | null;
    /**
     * Tip
     */
    tip?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HintOut
 *
 * A nudge, never the answer: taking it halves the XP for the question.
 */
export type HintOut = {
    /**
     * Text
     */
    text: string;
    /**
     * Removed Options
     *
     * Options the hint rules out
     */
    removed_options: Array<number>;
};

/**
 * InviteIn
 */
export type InviteIn = {
    role?: Role;
    vertical?: Vertical | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * InviteInfo
 */
export type InviteInfo = {
    role: Role;
    vertical: Vertical | null;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * KeyIn
 *
 * An answer as options picked or a typed value.
 */
export type KeyIn = {
    /**
     * Options
     */
    options?: Array<number> | null;
    /**
     * Value
     */
    value?: string | null;
};

/**
 * LeaderRow
 */
export type LeaderRow = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Display Name
     */
    display_name: string;
    vertical: Vertical | null;
    /**
     * Score
     *
     * Rank points on the ranked board (season, everyone); LP won on the others
     */
    score: number;
    /**
     * Me
     */
    me: boolean;
    /**
     * Division
     *
     * Current division (0 = Mingo I … 15 = the top), for the emblem
     */
    division: number;
    /**
     * Title
     */
    title: string;
    /**
     * Level
     *
     * Account level
     */
    level: number;
};

/**
 * Leaderboard
 */
export type Leaderboard = {
    /**
     * Period
     */
    period: 'season' | 'week';
    /**
     * Board
     */
    board: 'everyone' | 'mech' | 'elec' | 'rules';
    /**
     * Rows
     */
    rows: Array<LeaderRow>;
    /**
     * Null until the member scores in this period
     */
    me: MyRank | null;
    /**
     * Players
     *
     * People on this board, including any beyond the rows shown
     */
    players: number;
};

/**
 * Learning
 *
 * A topic's panels; empty lists where the player's level has taken them away.
 */
export type Learning = {
    /**
     * Title
     */
    title: string;
    /**
     * Formulas
     */
    formulas: Array<Formula>;
    /**
     * Learn More
     */
    learn_more: Array<Reading>;
};

/**
 * Link
 */
export type Link = {
    /**
     * Url
     */
    url: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * LiveConfig
 *
 * How the host wants the quiz to go (ADR 0005).
 */
export type LiveConfig = {
    /**
     * Questions
     */
    questions?: 'areas' | 'quiz';
    /**
     * Areas
     */
    areas?: Array<'mech' | 'elec' | 'rules'>;
    /**
     * Topics
     */
    topics?: Array<string>;
    /**
     * Quiz Id
     */
    quiz_id?: number | null;
    /**
     * Count
     */
    count?: number;
    /**
     * Timing
     */
    timing?: 'real' | 'fixed' | 'host';
    /**
     * Seconds
     */
    seconds?: number;
    /**
     * Feedback
     */
    feedback?: 'each' | 'end';
    /**
     * Speed Points
     */
    speed_points?: boolean;
    /**
     * Routing
     *
     * all: every table answers every question; owners: each goes to the table owning its topic
     */
    routing?: 'all' | 'owners';
};

/**
 * LiveCreated
 */
export type LiveCreated = {
    /**
     * Code
     */
    code: string;
};

/**
 * LivePlayerOut
 */
export type LivePlayerOut = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Table Id
     */
    table_id: number | null;
};

/**
 * LiveReveal
 */
export type LiveReveal = {
    /**
     * Position
     */
    position: number;
    question: PlayQuestion;
    /**
     * Table Id
     *
     * The table that answered for the room; null when every table did
     */
    table_id: number | null;
    feedback: Feedback;
    /**
     * Answers
     */
    answers: Array<TableAnswer>;
};

/**
 * LiveState
 *
 * What one person sees of a live quiz. Right and wrong appear only once a question closes (or at the end
 * of a rehearsal).
 */
export type LiveState = {
    /**
     * Code
     */
    code: string;
    /**
     * State
     */
    state: 'lobby' | 'open' | 'closed' | 'finished';
    /**
     * Host Name
     */
    host_name: string;
    config: LiveConfig;
    /**
     * Role
     */
    role: 'host' | 'player';
    /**
     * My Table Id
     */
    my_table_id: number | null;
    /**
     * Captain
     */
    captain: boolean;
    /**
     * Position
     */
    position: number;
    /**
     * Total
     */
    total: number;
    /**
     * Deadline At
     */
    deadline_at: string | null;
    /**
     * Server Now
     */
    server_now: string;
    /**
     * Version
     */
    version: number;
    /**
     * Players
     */
    players: Array<LivePlayerOut>;
    /**
     * Tables
     */
    tables: Array<LiveTableOut>;
    question?: PlayQuestion | null;
    /**
     * Question Table Id
     */
    question_table_id?: number | null;
    /**
     * Budget S
     */
    budget_s?: number | null;
    /**
     * What the table answering sent, while it is open
     */
    my_answer?: KeyIn | null;
    /**
     * Proposals
     */
    proposals?: Array<Proposal>;
    /**
     * Reveals
     */
    reveals?: Array<LiveReveal>;
    /**
     * Room Right
     */
    room_right?: number | null;
    /**
     * Room Asked
     */
    room_asked?: number;
    /**
     * Bar To Beat
     */
    bar_to_beat?: string | null;
};

/**
 * LiveTableOut
 */
export type LiveTableOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Captain Id
     */
    captain_id: number | null;
    /**
     * Topics
     */
    topics: Array<string>;
    /**
     * Catch All
     */
    catch_all: boolean;
    /**
     * Member Ids
     */
    member_ids: Array<number>;
    /**
     * Answered
     *
     * Has sent its answer to the current question
     */
    answered: boolean;
    /**
     * Right
     *
     * Right answers so far, once they may be shown
     */
    right: number;
    /**
     * Points
     */
    points: number;
    /**
     * Reach
     *
     * In the lobby of a specialists quiz: the share of draws of this quiz's questions in which the table gets at least one (0 without a captain); null otherwise
     */
    reach?: number | null;
};

/**
 * LoginIn
 */
export type LoginIn = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Me
 */
export type Me = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    vertical: Vertical | null;
    role: Role;
    /**
     * Leaderboard Opt Out
     */
    leaderboard_opt_out: boolean;
    position: Position;
    /**
     * Xp
     */
    xp: number;
    /**
     * Subdepartments
     */
    subdepartments: Array<string>;
    /**
     * Can Host
     *
     * May host a live quiz: TDs by position, and admins
     */
    can_host?: boolean;
    progress?: Progress | null;
};

/**
 * MockAnswerIn
 */
export type MockAnswerIn = {
    /**
     * Options
     */
    options?: Array<number> | null;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Unsure
     *
     * "I'm not sure": no answer; the official one shown for half a wrong answer's LP
     */
    unsure?: boolean;
    /**
     * Attempt Id
     */
    attempt_id: number;
};

/**
 * MockItem
 */
export type MockItem = {
    question: PlayQuestion;
    feedback: Feedback;
    /**
     * What you sent; none if the time ran out
     */
    answer?: KeyIn | null;
    /**
     * Late
     */
    late: boolean;
};

/**
 * MockQuiz
 */
export type MockQuiz = {
    /**
     * Id
     */
    id: number;
    /**
     * Label
     */
    label: string;
    /**
     * Year
     */
    year: number;
    /**
     * Vehicle Class
     */
    vehicle_class: string;
    /**
     * Held On
     */
    held_on: string | null;
    /**
     * Questions
     */
    questions: number;
    /**
     * Graded
     */
    graded: number;
    /**
     * Total Time S
     */
    total_time_s: number | null;
    /**
     * Bar To Beat
     */
    bar_to_beat: string | null;
    /**
     * Best
     *
     * Most correct answers in a finished run
     */
    best: number | null;
    /**
     * Open Session
     */
    open_session: number | null;
};

/**
 * MockState
 */
export type MockState = {
    /**
     * Session Id
     */
    session_id: number;
    /**
     * Quiz Id
     */
    quiz_id: number;
    /**
     * Label
     */
    label: string;
    /**
     * Position
     *
     * Questions already answered
     */
    position: number;
    /**
     * Total
     */
    total: number;
    current: TimedQuestion | null;
    summary: MockSummary | null;
};

/**
 * MockSummary
 */
export type MockSummary = {
    /**
     * Correct
     */
    correct: number;
    /**
     * Graded
     */
    graded: number;
    /**
     * Xp
     */
    xp: number;
    /**
     * Lp
     */
    lp: number;
    /**
     * Counted
     */
    counted: boolean;
    /**
     * Bar To Beat
     */
    bar_to_beat: string | null;
    /**
     * Items
     */
    items: Array<MockItem>;
};

/**
 * MoveIn
 */
export type MoveIn = {
    /**
     * Table Id
     */
    table_id: number | null;
};

/**
 * MyRank
 *
 * The requesting member's own place, shown even when they are hidden or outside the top rows.
 */
export type MyRank = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Score
     */
    score: number;
    /**
     * Hidden
     *
     * Opted out: others don't see them on the board
     */
    hidden: boolean;
};

/**
 * OpenInvite
 */
export type OpenInvite = {
    /**
     * Id
     */
    id: number;
    role: Role;
    vertical: Vertical | null;
    /**
     * Note
     */
    note: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * Option
 */
export type Option = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
};

/**
 * PasswordChangeIn
 */
export type PasswordChangeIn = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PlayQuestion
 *
 * A question before it is answered: nothing here may reveal the answer.
 */
export type PlayQuestion = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
    /**
     * Answer Kind
     */
    answer_kind: string;
    /**
     * Graded
     */
    graded: boolean;
    /**
     * Values
     *
     * How many values a list answer needs, when known
     */
    values: number | null;
    /**
     * Time S
     */
    time_s: number | null;
    /**
     * Area
     */
    area: string;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Images
     */
    images: Array<string>;
    /**
     * Options
     */
    options: Array<Option>;
    /**
     * Quizzes
     */
    quizzes: Array<string>;
    documents: QuestionDocs;
};

/**
 * Position
 *
 * Someone's job on the team. Not their XP level: a DT on the ladder is not a Technical Director.
 */
export const Position = {
    MINGO: 'mingo',
    MEMBER: 'member',
    DEPARTMENT_HEAD: 'department_head',
    TECHNICAL_DIRECTOR: 'technical_director'
} as const;

/**
 * Position
 *
 * Someone's job on the team. Not their XP level: a DT on the ladder is not a Technical Director.
 */
export type Position = typeof Position[keyof typeof Position];

/**
 * ProfileIn
 */
export type ProfileIn = {
    /**
     * Display Name
     */
    display_name?: string | null;
    vertical?: Vertical | null;
    /**
     * Leaderboard Opt Out
     */
    leaderboard_opt_out?: boolean | null;
    /**
     * Subdepartments
     */
    subdepartments?: Array<string> | null;
};

/**
 * Progress
 */
export type Progress = {
    rank: RankOut;
    account: AccountOut;
};

/**
 * Proposal
 */
export type Proposal = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Options
     */
    options?: Array<number> | null;
    /**
     * Value
     */
    value?: string | null;
};

/**
 * QuestionDocs
 *
 * The rulebook, handbook and other documents the question's quizzes were based on.
 */
export type QuestionDocs = {
    /**
     * Year
     *
     * Year of the newest of them
     */
    year: number | null;
    /**
     * Used
     */
    used: Array<DocLink>;
    /**
     * Newer
     *
     * Later editions of those rulebooks and handbooks: rules may have changed
     */
    newer: Array<DocLink>;
};

/**
 * RankOut
 *
 * The rank (ADR 0007): divisions of 100 LP that go up and down with how well you answer.
 */
export type RankOut = {
    /**
     * Points
     */
    points: number;
    /**
     * Division
     */
    division: number;
    /**
     * Title
     */
    title: string;
    /**
     * Tier
     */
    tier: 'Mingo' | 'Jefe' | 'DT' | 'Top';
    /**
     * Lp
     *
     * LP into the division; uncapped at the top
     */
    lp: number;
    /**
     * Stakes
     */
    stakes: number;
    /**
     * Swing
     *
     * A middling daily question right and wrong, at this rank
     */
    swing: [
        number,
        number
    ];
    /**
     * Miss Streak
     *
     * Wrong answers in a row; from 3 losses halve and a right one pays 1.5x
     */
    miss_streak: number;
    aids: Aids;
    /**
     * Ladder
     */
    ladder: Array<Step>;
};

/**
 * Reading
 */
export type Reading = {
    /**
     * Title
     */
    title: string;
    /**
     * Url
     */
    url: string;
    /**
     * Note
     */
    note: string;
};

/**
 * RegisterIn
 */
export type RegisterIn = {
    /**
     * Token
     */
    token: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Password
     */
    password: string;
    vertical?: Vertical | null;
    /**
     * Job on the team; sets the starting level
     */
    position?: Position;
};

/**
 * ReportIn
 */
export type ReportIn = {
    /**
     * Message
     */
    message: string;
};

/**
 * ResetIn
 */
export type ResetIn = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ResetInfo
 */
export type ResetInfo = {
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * ReviewOption
 */
export type ReviewOption = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
    /**
     * Official
     */
    official: boolean;
    /**
     * Corrected
     */
    corrected: boolean;
};

/**
 * ReviewPage
 */
export type ReviewPage = {
    /**
     * Rows
     */
    rows: Array<ReviewRow>;
    /**
     * Total
     */
    total: number;
    /**
     * Queues
     */
    queues: {
        [key: string]: number;
    };
};

/**
 * ReviewPatch
 */
export type ReviewPatch = {
    /**
     * Area
     */
    area?: 'mech' | 'elec' | 'rules' | 'unclassified' | null;
    /**
     * Topic
     */
    topic?: string | null;
    /**
     * Labels Reviewed
     */
    labels_reviewed?: boolean | null;
    /**
     * Excluded
     */
    excluded?: boolean | null;
    /**
     * Exclusion Note
     */
    exclusion_note?: string | null;
    /**
     * Acknowledge Change
     */
    acknowledge_change?: boolean | null;
};

/**
 * ReviewQuestion
 *
 * Everything a reviewer needs about one question, answers included (reviewers only).
 */
export type ReviewQuestion = {
    /**
     * Id
     */
    id: number;
    /**
     * Fsquiz Id
     */
    fsquiz_id: number | null;
    /**
     * Type
     */
    type: string;
    /**
     * Text
     */
    text: string;
    /**
     * Images
     */
    images: Array<string>;
    /**
     * Area
     */
    area: string;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Labels Reviewed
     */
    labels_reviewed: boolean;
    /**
     * Answer Kind
     */
    answer_kind: string;
    /**
     * Graded
     */
    graded: boolean;
    /**
     * Playable
     */
    playable: boolean;
    /**
     * Images Missing
     */
    images_missing: boolean;
    /**
     * Excluded
     */
    excluded: boolean;
    /**
     * Exclusion Note
     */
    exclusion_note: string | null;
    /**
     * Key Changed At
     */
    key_changed_at: string | null;
    /**
     * Official
     */
    official: string | null;
    /**
     * Correction
     */
    correction: string | null;
    /**
     * Options
     */
    options: Array<ReviewOption>;
    /**
     * Quizzes
     */
    quizzes: Array<string>;
    /**
     * Reports
     */
    reports: Array<ReviewReport>;
    /**
     * Answered
     */
    answered: number;
    /**
     * Right
     */
    right: number;
    /**
     * Answer Hidden
     *
     * The reviewer's own live question: answers withheld until answered
     */
    answer_hidden: boolean;
    /**
     * Quiz Notes
     *
     * FS-Quiz's notes on the quizzes it appeared in, e.g. that a question was later removed
     */
    quiz_notes: Array<string>;
};

/**
 * ReviewReport
 */
export type ReviewReport = {
    /**
     * Id
     */
    id: number;
    /**
     * By
     */
    by: string | null;
    /**
     * Message
     */
    message: string;
    /**
     * At
     */
    at: string;
};

/**
 * ReviewRow
 */
export type ReviewRow = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
    /**
     * Area
     */
    area: string;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Answer Kind
     */
    answer_kind: string;
    /**
     * Graded
     */
    graded: boolean;
    /**
     * Playable
     */
    playable: boolean;
    /**
     * Excluded
     */
    excluded: boolean;
    /**
     * Labels Reviewed
     */
    labels_reviewed: boolean;
    /**
     * Key Changed At
     */
    key_changed_at: string | null;
    /**
     * Reports
     */
    reports: number;
};

/**
 * Role
 */
export const Role = {
    MEMBER: 'member',
    REVIEWER: 'reviewer',
    ADMIN: 'admin'
} as const;

/**
 * Role
 */
export type Role = typeof Role[keyof typeof Role];

/**
 * SeatIn
 */
export type SeatIn = {
    /**
     * Tables
     */
    tables: Array<TableIn>;
};

/**
 * SolutionOut
 */
export type SolutionOut = {
    /**
     * Text
     */
    text: string | null;
    /**
     * Images
     */
    images: Array<string>;
};

/**
 * Status
 */
export const Status = {
    ACTIVE: 'active',
    ALUMNI: 'alumni',
    DISABLED: 'disabled'
} as const;

/**
 * Status
 */
export type Status = typeof Status[keyof typeof Status];

/**
 * Step
 *
 * One division of the ladder and what it changes.
 */
export type Step = {
    /**
     * Division
     */
    division: number;
    /**
     * Tier
     */
    tier: 'Mingo' | 'Jefe' | 'DT' | 'Top';
    /**
     * Title
     *
     * Null for the top until the player reaches DT V: a surprise
     */
    title: string | null;
    /**
     * Points
     *
     * Rank points where it starts
     */
    points: number;
    aids: Aids;
    /**
     * Stakes
     *
     * How hard a wrong answer bites here, in percent (80 at Mingo I)
     */
    stakes: number;
};

/**
 * Subdepartment
 */
export type Subdepartment = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Vertical
     */
    vertical: string;
    /**
     * Topics
     */
    topics: Array<string>;
};

/**
 * TableAnswer
 */
export type TableAnswer = {
    /**
     * Table Id
     */
    table_id: number;
    /**
     * Correct
     */
    correct: boolean | null;
    /**
     * Passed
     */
    passed: boolean;
    /**
     * Points
     */
    points: number;
    /**
     * Options
     */
    options?: Array<number> | null;
    /**
     * Value
     */
    value?: string | null;
};

/**
 * TableEditIn
 */
export type TableEditIn = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Captain Id
     */
    captain_id?: number | null;
};

/**
 * TableIn
 */
export type TableIn = {
    /**
     * Name
     */
    name: string;
    /**
     * Captain Id
     */
    captain_id?: number | null;
    /**
     * Member Ids
     */
    member_ids: Array<number>;
    /**
     * Topics
     */
    topics?: Array<string>;
    /**
     * Catch All
     */
    catch_all?: boolean;
};

/**
 * TimedQuestion
 *
 * A question whose clock is running. `server_now` lets the browser correct for its own clock.
 */
export type TimedQuestion = {
    /**
     * Attempt Id
     */
    attempt_id: number;
    question: PlayQuestion;
    /**
     * Deadline At
     */
    deadline_at: string;
    /**
     * Server Now
     */
    server_now: string;
};

/**
 * TokenIn
 */
export type TokenIn = {
    /**
     * Token
     */
    token: string;
};

/**
 * UserPatch
 */
export type UserPatch = {
    /**
     * Email
     */
    email?: string | null;
    role?: Role | null;
    status?: Status | null;
    position?: Position | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Vertical
 */
export const Vertical = {
    MANAGEMENT: 'Management',
    MECHANICAL: 'Mechanical',
    TRACTIVE_SYSTEM: 'Tractive System',
    ELECTRONICS: 'Electronics',
    DRIVERLESS: 'Driverless',
    BUSINESS: 'Business',
    BOARD: 'Board'
} as const;

/**
 * Vertical
 */
export type Vertical = typeof Vertical[keyof typeof Vertical];

/**
 * VerticalBoard
 */
export type VerticalBoard = {
    /**
     * Period
     */
    period: 'season' | 'week';
    /**
     * Rows
     */
    rows: Array<VerticalRow>;
};

/**
 * VerticalRow
 */
export type VerticalRow = {
    vertical: Vertical;
    /**
     * Members
     */
    members: number;
    /**
     * Rank Points
     *
     * The members' average rank points
     */
    rank_points: number;
    /**
     * Participation
     *
     * Share of members who answered a daily question in the last 7 days
     */
    participation: number;
};

export type LoginData = {
    body: LoginIn;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type InviteInfoData = {
    body: TokenIn;
    path?: never;
    query?: never;
    url: '/auth/invites/lookup';
};

export type InviteInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteInfoError = InviteInfoErrors[keyof InviteInfoErrors];

export type InviteInfoResponses = {
    /**
     * Successful Response
     */
    200: InviteInfo;
};

export type InviteInfoResponse = InviteInfoResponses[keyof InviteInfoResponses];

export type RegisterData = {
    body: RegisterIn;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: Me;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type ResetInfoData = {
    body: TokenIn;
    path?: never;
    query?: never;
    url: '/auth/resets/lookup';
};

export type ResetInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetInfoError = ResetInfoErrors[keyof ResetInfoErrors];

export type ResetInfoResponses = {
    /**
     * Successful Response
     */
    200: ResetInfo;
};

export type ResetInfoResponse = ResetInfoResponses[keyof ResetInfoResponses];

export type ResetData = {
    body: ResetIn;
    path?: never;
    query?: never;
    url: '/auth/reset';
};

export type ResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetError = ResetErrors[keyof ResetErrors];

export type ResetResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResetResponse = ResetResponses[keyof ResetResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type UpdateMeData = {
    body: ProfileIn;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type UpdateMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type ChangePasswordData = {
    body: PasswordChangeIn;
    path?: never;
    query?: never;
    url: '/api/me/password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type ExportMyDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/export';
};

export type ExportMyDataResponses = {
    /**
     * Successful Response
     */
    200: Export;
};

export type ExportMyDataResponse = ExportMyDataResponses[keyof ExportMyDataResponses];

export type DeleteAccountData = {
    body: DeleteAccountIn;
    path?: never;
    query?: never;
    url: '/api/me/delete';
};

export type DeleteAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type UsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/users';
};

export type UsersResponses = {
    /**
     * Response Users
     *
     * Successful Response
     */
    200: Array<AdminUser>;
};

export type UsersResponse = UsersResponses[keyof UsersResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type UpdateUserData = {
    body: UserPatch;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: AdminUser;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ExportUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}/export';
};

export type ExportUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportUserError = ExportUserErrors[keyof ExportUserErrors];

export type ExportUserResponses = {
    /**
     * Successful Response
     */
    200: Export;
};

export type ExportUserResponse = ExportUserResponses[keyof ExportUserResponses];

export type MarkAlumniData = {
    body: AlumniIn;
    path?: never;
    query?: never;
    url: '/api/admin/alumni';
};

export type MarkAlumniErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkAlumniError = MarkAlumniErrors[keyof MarkAlumniErrors];

export type MarkAlumniResponses = {
    /**
     * Successful Response
     */
    200: AlumniOut;
};

export type MarkAlumniResponse = MarkAlumniResponses[keyof MarkAlumniResponses];

export type ResetLinkData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}/reset-link';
};

export type ResetLinkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetLinkError = ResetLinkErrors[keyof ResetLinkErrors];

export type ResetLinkResponses = {
    /**
     * Successful Response
     */
    201: Link;
};

export type ResetLinkResponse = ResetLinkResponses[keyof ResetLinkResponses];

export type RevokeSessionsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}/revoke-sessions';
};

export type RevokeSessionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeSessionsError = RevokeSessionsErrors[keyof RevokeSessionsErrors];

export type RevokeSessionsResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeSessionsResponse = RevokeSessionsResponses[keyof RevokeSessionsResponses];

export type OpenInvitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/invites';
};

export type OpenInvitesResponses = {
    /**
     * Response Open Invites
     *
     * Successful Response
     */
    200: Array<OpenInvite>;
};

export type OpenInvitesResponse = OpenInvitesResponses[keyof OpenInvitesResponses];

export type CreateInviteData = {
    body: InviteIn;
    path?: never;
    query?: never;
    url: '/api/admin/invites';
};

export type CreateInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInviteError = CreateInviteErrors[keyof CreateInviteErrors];

export type CreateInviteResponses = {
    /**
     * Successful Response
     */
    201: Link;
};

export type CreateInviteResponse = CreateInviteResponses[keyof CreateInviteResponses];

export type RevokeInviteData = {
    body?: never;
    path: {
        /**
         * Invite Id
         */
        invite_id: number;
    };
    query?: never;
    url: '/api/admin/invites/{invite_id}';
};

export type RevokeInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeInviteError = RevokeInviteErrors[keyof RevokeInviteErrors];

export type RevokeInviteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeInviteResponse = RevokeInviteResponses[keyof RevokeInviteResponses];

export type AuditLogData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/admin/audit';
};

export type AuditLogErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuditLogError = AuditLogErrors[keyof AuditLogErrors];

export type AuditLogResponses = {
    /**
     * Response Audit Log
     *
     * Successful Response
     */
    200: Array<AuditEntry>;
};

export type AuditLogResponse = AuditLogResponses[keyof AuditLogResponses];

export type BankSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/bank';
};

export type BankSummaryResponses = {
    /**
     * Successful Response
     */
    200: BankSummary;
};

export type BankSummaryResponse = BankSummaryResponses[keyof BankSummaryResponses];

export type PracticeAreasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/practice/areas';
};

export type PracticeAreasResponses = {
    /**
     * Response Practice Areas
     *
     * Successful Response
     */
    200: Array<AreaProgress>;
};

export type PracticeAreasResponse = PracticeAreasResponses[keyof PracticeAreasResponses];

export type NextQuestionData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Area
         */
        area?: 'mech' | 'elec' | 'rules' | 'unclassified' | null;
        /**
         * Topic
         */
        topic?: string | null;
        /**
         * Skip
         */
        skip?: number | null;
    };
    url: '/api/practice/next';
};

export type NextQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NextQuestionError = NextQuestionErrors[keyof NextQuestionErrors];

export type NextQuestionResponses = {
    /**
     * Successful Response
     */
    200: PlayQuestion;
};

export type NextQuestionResponse = NextQuestionResponses[keyof NextQuestionResponses];

export type PracticeQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/practice/questions/{question_id}';
};

export type PracticeQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PracticeQuestionError = PracticeQuestionErrors[keyof PracticeQuestionErrors];

export type PracticeQuestionResponses = {
    /**
     * Successful Response
     */
    200: PlayQuestion;
};

export type PracticeQuestionResponse = PracticeQuestionResponses[keyof PracticeQuestionResponses];

export type AnswerPracticeData = {
    body: AnswerIn;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/practice/questions/{question_id}/answer';
};

export type AnswerPracticeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerPracticeError = AnswerPracticeErrors[keyof AnswerPracticeErrors];

export type AnswerPracticeResponses = {
    /**
     * Successful Response
     */
    200: Feedback;
};

export type AnswerPracticeResponse = AnswerPracticeResponses[keyof AnswerPracticeResponses];

export type PracticeHintData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/practice/questions/{question_id}/hint';
};

export type PracticeHintErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PracticeHintError = PracticeHintErrors[keyof PracticeHintErrors];

export type PracticeHintResponses = {
    /**
     * Successful Response
     */
    200: HintOut;
};

export type PracticeHintResponse = PracticeHintResponses[keyof PracticeHintResponses];

export type DailyStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/daily';
};

export type DailyStatusResponses = {
    /**
     * Successful Response
     */
    200: DailyStatus;
};

export type DailyStatusResponse = DailyStatusResponses[keyof DailyStatusResponses];

export type StartDailyData = {
    body?: never;
    path: {
        /**
         * Area
         */
        area: 'mech' | 'elec' | 'rules';
    };
    query?: never;
    url: '/api/daily/{area}/start';
};

export type StartDailyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartDailyError = StartDailyErrors[keyof StartDailyErrors];

export type StartDailyResponses = {
    /**
     * Successful Response
     */
    200: TimedQuestion;
};

export type StartDailyResponse = StartDailyResponses[keyof StartDailyResponses];

export type AnswerDailyData = {
    body: AnswerIn;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: number;
    };
    query?: never;
    url: '/api/daily/attempts/{attempt_id}/answer';
};

export type AnswerDailyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerDailyError = AnswerDailyErrors[keyof AnswerDailyErrors];

export type AnswerDailyResponses = {
    /**
     * Successful Response
     */
    200: DailyResult;
};

export type AnswerDailyResponse = AnswerDailyResponses[keyof AnswerDailyResponses];

export type ReviewDailyData = {
    body?: never;
    path: {
        /**
         * Area
         */
        area: 'mech' | 'elec' | 'rules';
    };
    query?: never;
    url: '/api/daily/{area}/review';
};

export type ReviewDailyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewDailyError = ReviewDailyErrors[keyof ReviewDailyErrors];

export type ReviewDailyResponses = {
    /**
     * Successful Response
     */
    200: DailyResult;
};

export type ReviewDailyResponse = ReviewDailyResponses[keyof ReviewDailyResponses];

export type DailyHintData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: number;
    };
    query?: never;
    url: '/api/daily/attempts/{attempt_id}/hint';
};

export type DailyHintErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DailyHintError = DailyHintErrors[keyof DailyHintErrors];

export type DailyHintResponses = {
    /**
     * Successful Response
     */
    200: HintOut;
};

export type DailyHintResponse = DailyHintResponses[keyof DailyHintResponses];

export type MockQuizzesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mock/quizzes';
};

export type MockQuizzesResponses = {
    /**
     * Response Mock Quizzes
     *
     * Successful Response
     */
    200: Array<MockQuiz>;
};

export type MockQuizzesResponse = MockQuizzesResponses[keyof MockQuizzesResponses];

export type StartMockData = {
    body?: never;
    path: {
        /**
         * Quiz Id
         */
        quiz_id: number;
    };
    query?: never;
    url: '/api/mock/quizzes/{quiz_id}/start';
};

export type StartMockErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartMockError = StartMockErrors[keyof StartMockErrors];

export type StartMockResponses = {
    /**
     * Successful Response
     */
    200: MockState;
};

export type StartMockResponse = StartMockResponses[keyof StartMockResponses];

export type MockStateData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: number;
    };
    query?: never;
    url: '/api/mock/sessions/{session_id}';
};

export type MockStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MockStateError = MockStateErrors[keyof MockStateErrors];

export type MockStateResponses = {
    /**
     * Successful Response
     */
    200: MockState;
};

export type MockStateResponse = MockStateResponses[keyof MockStateResponses];

export type AnswerMockData = {
    body: MockAnswerIn;
    path: {
        /**
         * Session Id
         */
        session_id: number;
    };
    query?: never;
    url: '/api/mock/sessions/{session_id}/answer';
};

export type AnswerMockErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerMockError = AnswerMockErrors[keyof AnswerMockErrors];

export type AnswerMockResponses = {
    /**
     * Successful Response
     */
    200: MockState;
};

export type AnswerMockResponse = AnswerMockResponses[keyof AnswerMockResponses];

export type MockHintData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: number;
        /**
         * Attempt Id
         */
        attempt_id: number;
    };
    query?: never;
    url: '/api/mock/sessions/{session_id}/attempts/{attempt_id}/hint';
};

export type MockHintErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MockHintError = MockHintErrors[keyof MockHintErrors];

export type MockHintResponses = {
    /**
     * Successful Response
     */
    200: HintOut;
};

export type MockHintResponse = MockHintResponses[keyof MockHintResponses];

export type ReviewQuestionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Queue
         */
        queue?: 'all' | 'reports' | 'changed' | 'unclassified' | 'ungraded' | 'excluded';
        /**
         * Area
         */
        area?: 'mech' | 'elec' | 'rules' | 'unclassified' | null;
        /**
         * Topic
         */
        topic?: string | null;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/review/questions';
};

export type ReviewQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewQuestionsError = ReviewQuestionsErrors[keyof ReviewQuestionsErrors];

export type ReviewQuestionsResponses = {
    /**
     * Successful Response
     */
    200: ReviewPage;
};

export type ReviewQuestionsResponse = ReviewQuestionsResponses[keyof ReviewQuestionsResponses];

export type ReviewQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/review/questions/{question_id}';
};

export type ReviewQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewQuestionError = ReviewQuestionErrors[keyof ReviewQuestionErrors];

export type ReviewQuestionResponses = {
    /**
     * Successful Response
     */
    200: ReviewQuestion;
};

export type ReviewQuestionResponse = ReviewQuestionResponses[keyof ReviewQuestionResponses];

export type UpdateQuestionData = {
    body: ReviewPatch;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/review/questions/{question_id}';
};

export type UpdateQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateQuestionError = UpdateQuestionErrors[keyof UpdateQuestionErrors];

export type UpdateQuestionResponses = {
    /**
     * Successful Response
     */
    200: ReviewQuestion;
};

export type UpdateQuestionResponse = UpdateQuestionResponses[keyof UpdateQuestionResponses];

export type RemoveCorrectionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/review/questions/{question_id}/answer';
};

export type RemoveCorrectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveCorrectionError = RemoveCorrectionErrors[keyof RemoveCorrectionErrors];

export type RemoveCorrectionResponses = {
    /**
     * Successful Response
     */
    200: ReviewQuestion;
};

export type RemoveCorrectionResponse = RemoveCorrectionResponses[keyof RemoveCorrectionResponses];

export type CorrectAnswerData = {
    body: KeyIn;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/review/questions/{question_id}/answer';
};

export type CorrectAnswerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CorrectAnswerError = CorrectAnswerErrors[keyof CorrectAnswerErrors];

export type CorrectAnswerResponses = {
    /**
     * Successful Response
     */
    200: ReviewQuestion;
};

export type CorrectAnswerResponse = CorrectAnswerResponses[keyof CorrectAnswerResponses];

export type ResolveReportData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: number;
    };
    query?: never;
    url: '/api/review/reports/{report_id}/resolve';
};

export type ResolveReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveReportError = ResolveReportErrors[keyof ResolveReportErrors];

export type ResolveReportResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResolveReportResponse = ResolveReportResponses[keyof ResolveReportResponses];

export type ReportQuestionData = {
    body: ReportIn;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/api/questions/{question_id}/report';
};

export type ReportQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportQuestionError = ReportQuestionErrors[keyof ReportQuestionErrors];

export type ReportQuestionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ReportQuestionResponse = ReportQuestionResponses[keyof ReportQuestionResponses];

export type GetLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Board
         */
        board?: 'everyone' | 'mech' | 'elec' | 'rules';
        /**
         * Period
         */
        period?: 'season' | 'week';
    };
    url: '/api/leaderboard';
};

export type GetLeaderboardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLeaderboardError = GetLeaderboardErrors[keyof GetLeaderboardErrors];

export type GetLeaderboardResponses = {
    /**
     * Successful Response
     */
    200: Leaderboard;
};

export type GetLeaderboardResponse = GetLeaderboardResponses[keyof GetLeaderboardResponses];

export type VerticalLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Period
         */
        period?: 'season' | 'week';
    };
    url: '/api/leaderboard/verticals';
};

export type VerticalLeaderboardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerticalLeaderboardError = VerticalLeaderboardErrors[keyof VerticalLeaderboardErrors];

export type VerticalLeaderboardResponses = {
    /**
     * Successful Response
     */
    200: VerticalBoard;
};

export type VerticalLeaderboardResponse = VerticalLeaderboardResponses[keyof VerticalLeaderboardResponses];

export type TopicAidsData = {
    body?: never;
    path: {
        /**
         * Topic
         */
        topic: string;
    };
    query?: never;
    url: '/api/learning/{topic}';
};

export type TopicAidsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TopicAidsError = TopicAidsErrors[keyof TopicAidsErrors];

export type TopicAidsResponses = {
    /**
     * Successful Response
     */
    200: Learning;
};

export type TopicAidsResponse = TopicAidsResponses[keyof TopicAidsResponses];

export type SubdepartmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/live/subdepartments';
};

export type SubdepartmentsResponses = {
    /**
     * Response Subdepartments
     *
     * Successful Response
     */
    200: Array<Subdepartment>;
};

export type SubdepartmentsResponse = SubdepartmentsResponses[keyof SubdepartmentsResponses];

export type CreateSessionData = {
    body: LiveConfig;
    path?: never;
    query?: never;
    url: '/api/live/sessions';
};

export type CreateSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSessionError = CreateSessionErrors[keyof CreateSessionErrors];

export type CreateSessionResponses = {
    /**
     * Successful Response
     */
    201: LiveCreated;
};

export type CreateSessionResponse = CreateSessionResponses[keyof CreateSessionResponses];

export type SessionStateData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}';
};

export type SessionStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SessionStateError = SessionStateErrors[keyof SessionStateErrors];

export type SessionStateResponses = {
    /**
     * Successful Response
     */
    200: LiveState;
};

export type SessionStateResponse = SessionStateResponses[keyof SessionStateResponses];

export type JoinSessionData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/join';
};

export type JoinSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JoinSessionError = JoinSessionErrors[keyof JoinSessionErrors];

export type JoinSessionResponses = {
    /**
     * Successful Response
     */
    200: LiveState;
};

export type JoinSessionResponse = JoinSessionResponses[keyof JoinSessionResponses];

export type ConfigureSessionData = {
    body: LiveConfig;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/config';
};

export type ConfigureSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfigureSessionError = ConfigureSessionErrors[keyof ConfigureSessionErrors];

export type ConfigureSessionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ConfigureSessionResponse = ConfigureSessionResponses[keyof ConfigureSessionResponses];

export type SeatTablesData = {
    body: SeatIn;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/tables';
};

export type SeatTablesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SeatTablesError = SeatTablesErrors[keyof SeatTablesErrors];

export type SeatTablesResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type SeatTablesResponse = SeatTablesResponses[keyof SeatTablesResponses];

export type SeatBySubdepartmentData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/tables/auto';
};

export type SeatBySubdepartmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SeatBySubdepartmentError = SeatBySubdepartmentErrors[keyof SeatBySubdepartmentErrors];

export type SeatBySubdepartmentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type SeatBySubdepartmentResponse = SeatBySubdepartmentResponses[keyof SeatBySubdepartmentResponses];

export type EditTableData = {
    body: TableEditIn;
    path: {
        /**
         * Code
         */
        code: string;
        /**
         * Table Id
         */
        table_id: number;
    };
    query?: never;
    url: '/api/live/sessions/{code}/tables/{table_id}';
};

export type EditTableErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditTableError = EditTableErrors[keyof EditTableErrors];

export type EditTableResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type EditTableResponse = EditTableResponses[keyof EditTableResponses];

export type RemovePlayerData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/live/sessions/{code}/players/{user_id}';
};

export type RemovePlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemovePlayerError = RemovePlayerErrors[keyof RemovePlayerErrors];

export type RemovePlayerResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemovePlayerResponse = RemovePlayerResponses[keyof RemovePlayerResponses];

export type MovePlayerData = {
    body: MoveIn;
    path: {
        /**
         * Code
         */
        code: string;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/live/sessions/{code}/players/{user_id}';
};

export type MovePlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MovePlayerError = MovePlayerErrors[keyof MovePlayerErrors];

export type MovePlayerResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type MovePlayerResponse = MovePlayerResponses[keyof MovePlayerResponses];

export type AdvanceSessionData = {
    /**
     * Body
     */
    body?: AdvanceIn | null;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/advance';
};

export type AdvanceSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdvanceSessionError = AdvanceSessionErrors[keyof AdvanceSessionErrors];

export type AdvanceSessionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AdvanceSessionResponse = AdvanceSessionResponses[keyof AdvanceSessionResponses];

export type EndSessionData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/end';
};

export type EndSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EndSessionError = EndSessionErrors[keyof EndSessionErrors];

export type EndSessionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type EndSessionResponse = EndSessionResponses[keyof EndSessionResponses];

export type ProposeData = {
    body: KeyIn;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/proposal';
};

export type ProposeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProposeError = ProposeErrors[keyof ProposeErrors];

export type ProposeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ProposeResponse = ProposeResponses[keyof ProposeResponses];

export type AnswerData = {
    body: AnswerIn;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/answer';
};

export type AnswerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerError = AnswerErrors[keyof AnswerErrors];

export type AnswerResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AnswerResponse = AnswerResponses[keyof AnswerResponses];

export type ResultsData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/results.csv';
};

export type ResultsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResultsError = ResultsErrors[keyof ResultsErrors];

export type ResultsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EventsData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/live/sessions/{code}/events';
};

export type EventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventsError = EventsErrors[keyof EventsErrors];

export type EventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
