// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { auditLog, bankSummary, changePassword, createInvite, inviteInfo, login, logout, me, openInvites, type Options, register, reset, resetInfo, resetLink, revokeInvite, revokeSessions, updateMe, updateUser, users } from '../sdk.gen';
import type { AuditLogData, AuditLogError, AuditLogResponse, BankSummaryData, BankSummaryResponse, ChangePasswordData, ChangePasswordError, ChangePasswordResponse, CreateInviteData, CreateInviteError, CreateInviteResponse, InviteInfoData, InviteInfoError, InviteInfoResponse, LoginData, LoginError, LoginResponse, LogoutData, LogoutResponse, MeData, MeResponse, OpenInvitesData, OpenInvitesResponse, RegisterData, RegisterError, RegisterResponse, ResetData, ResetError, ResetInfoData, ResetInfoError, ResetInfoResponse, ResetLinkData, ResetLinkError, ResetLinkResponse, ResetResponse, RevokeInviteData, RevokeInviteError, RevokeInviteResponse, RevokeSessionsData, RevokeSessionsError, RevokeSessionsResponse, UpdateMeData, UpdateMeError, UpdateMeResponse, UpdateUserData, UpdateUserError, UpdateUserResponse, UsersData, UsersResponse } from '../types.gen';

/**
 * Login
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Invite Info
 */
export const inviteInfoMutation = (options?: Partial<Options<InviteInfoData>>): UseMutationOptions<InviteInfoResponse, InviteInfoError, Options<InviteInfoData>> => {
    const mutationOptions: UseMutationOptions<InviteInfoResponse, InviteInfoError, Options<InviteInfoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await inviteInfo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reset Info
 */
export const resetInfoMutation = (options?: Partial<Options<ResetInfoData>>): UseMutationOptions<ResetInfoResponse, ResetInfoError, Options<ResetInfoData>> => {
    const mutationOptions: UseMutationOptions<ResetInfoResponse, ResetInfoError, Options<ResetInfoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await resetInfo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reset
 */
export const resetMutation = (options?: Partial<Options<ResetData>>): UseMutationOptions<ResetResponse, ResetError, Options<ResetData>> => {
    const mutationOptions: UseMutationOptions<ResetResponse, ResetError, Options<ResetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reset({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

/**
 * Me
 */
export const meOptions = (options?: Options<MeData>) => queryOptions<MeResponse, DefaultError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await me({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: meQueryKey(options)
});

/**
 * Update Me
 */
export const updateMeMutation = (options?: Partial<Options<UpdateMeData>>): UseMutationOptions<UpdateMeResponse, UpdateMeError, Options<UpdateMeData>> => {
    const mutationOptions: UseMutationOptions<UpdateMeResponse, UpdateMeError, Options<UpdateMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Change Password
 */
export const changePasswordMutation = (options?: Partial<Options<ChangePasswordData>>): UseMutationOptions<ChangePasswordResponse, ChangePasswordError, Options<ChangePasswordData>> => {
    const mutationOptions: UseMutationOptions<ChangePasswordResponse, ChangePasswordError, Options<ChangePasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changePassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersQueryKey = (options?: Options<UsersData>) => createQueryKey('users', options);

/**
 * Users
 */
export const usersOptions = (options?: Options<UsersData>) => queryOptions<UsersResponse, DefaultError, UsersResponse, ReturnType<typeof usersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await users({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersQueryKey(options)
});

/**
 * Update User
 */
export const updateUserMutation = (options?: Partial<Options<UpdateUserData>>): UseMutationOptions<UpdateUserResponse, UpdateUserError, Options<UpdateUserData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserResponse, UpdateUserError, Options<UpdateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reset Link
 */
export const resetLinkMutation = (options?: Partial<Options<ResetLinkData>>): UseMutationOptions<ResetLinkResponse, ResetLinkError, Options<ResetLinkData>> => {
    const mutationOptions: UseMutationOptions<ResetLinkResponse, ResetLinkError, Options<ResetLinkData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await resetLink({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Revoke Sessions
 */
export const revokeSessionsMutation = (options?: Partial<Options<RevokeSessionsData>>): UseMutationOptions<RevokeSessionsResponse, RevokeSessionsError, Options<RevokeSessionsData>> => {
    const mutationOptions: UseMutationOptions<RevokeSessionsResponse, RevokeSessionsError, Options<RevokeSessionsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await revokeSessions({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const openInvitesQueryKey = (options?: Options<OpenInvitesData>) => createQueryKey('openInvites', options);

/**
 * Open Invites
 */
export const openInvitesOptions = (options?: Options<OpenInvitesData>) => queryOptions<OpenInvitesResponse, DefaultError, OpenInvitesResponse, ReturnType<typeof openInvitesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await openInvites({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: openInvitesQueryKey(options)
});

/**
 * Create Invite
 */
export const createInviteMutation = (options?: Partial<Options<CreateInviteData>>): UseMutationOptions<CreateInviteResponse, CreateInviteError, Options<CreateInviteData>> => {
    const mutationOptions: UseMutationOptions<CreateInviteResponse, CreateInviteError, Options<CreateInviteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createInvite({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Revoke Invite
 */
export const revokeInviteMutation = (options?: Partial<Options<RevokeInviteData>>): UseMutationOptions<RevokeInviteResponse, RevokeInviteError, Options<RevokeInviteData>> => {
    const mutationOptions: UseMutationOptions<RevokeInviteResponse, RevokeInviteError, Options<RevokeInviteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await revokeInvite({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const auditLogQueryKey = (options?: Options<AuditLogData>) => createQueryKey('auditLog', options);

/**
 * Audit Log
 */
export const auditLogOptions = (options?: Options<AuditLogData>) => queryOptions<AuditLogResponse, AuditLogError, AuditLogResponse, ReturnType<typeof auditLogQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await auditLog({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: auditLogQueryKey(options)
});

export const bankSummaryQueryKey = (options?: Options<BankSummaryData>) => createQueryKey('bankSummary', options);

/**
 * Bank Summary
 */
export const bankSummaryOptions = (options?: Options<BankSummaryData>) => queryOptions<BankSummaryResponse, DefaultError, BankSummaryResponse, ReturnType<typeof bankSummaryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await bankSummary({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: bankSummaryQueryKey(options)
});
