"""privacy: alumni dates, live sessions outlive their host

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-24 10:08:06.408934

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013"
down_revision: str | Sequence[str] | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("live_sessions", "host_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("fk_live_sessions_host_id_users"), "live_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_live_sessions_host_id_users"),
        "live_sessions",
        "users",
        ["host_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("users", sa.Column("left_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Accounts already inactive start their year before deletion now; invite notes leave the audit log.
    op.execute("UPDATE users SET left_at = now() WHERE status <> 'active'")
    op.execute("UPDATE audit_log SET details = details - 'note' WHERE action = 'invite.create'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "left_at")
    op.execute("DELETE FROM live_sessions WHERE host_id IS NULL")
    op.drop_constraint(op.f("fk_live_sessions_host_id_users"), "live_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_live_sessions_host_id_users"),
        "live_sessions",
        "users",
        ["host_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("live_sessions", "host_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
