"""live quiz

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-23 23:18:54.533792

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | Sequence[str] | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_sessions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=16), server_default="lobby", nullable=False),
        sa.Column("position", sa.Integer(), server_default="-1", nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "state IN ('lobby', 'open', 'closed', 'finished')", name=op.f("ck_live_sessions_state")
        ),
        sa.ForeignKeyConstraint(
            ["host_id"], ["users.id"], name=op.f("fk_live_sessions_host_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_sessions")),
        sa.UniqueConstraint("code", name=op.f("uq_live_sessions_code")),
    )
    op.create_index(op.f("ix_live_sessions_host_id"), "live_sessions", ["host_id"], unique=False)
    op.create_table(
        "live_tables",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("captain_id", sa.Integer(), nullable=True),
        sa.Column("topics", postgresql.ARRAY(sa.String(length=16)), server_default="{}", nullable=False),
        sa.Column("catch_all", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["captain_id"], ["users.id"], name=op.f("fk_live_tables_captain_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["live_sessions.id"],
            name=op.f("fk_live_tables_session_id_live_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_tables")),
    )
    op.create_index(op.f("ix_live_tables_session_id"), "live_tables", ["session_id"], unique=False)
    op.create_table(
        "live_answers",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("passed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("points", sa.Integer(), server_default="0", nullable=False),
        sa.Column("by_user_id", sa.Integer(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["by_user_id"], ["users.id"], name=op.f("fk_live_answers_by_user_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["live_sessions.id"],
            name=op.f("fk_live_answers_session_id_live_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["live_tables.id"],
            name=op.f("fk_live_answers_table_id_live_tables"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", "position", "table_id", name=op.f("pk_live_answers")),
    )
    op.create_table(
        "live_players",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["live_sessions.id"],
            name=op.f("fk_live_players_session_id_live_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["live_tables.id"],
            name=op.f("fk_live_players_table_id_live_tables"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_live_players_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("session_id", "user_id", name=op.f("pk_live_players")),
    )
    op.create_table(
        "live_proposals",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["live_sessions.id"],
            name=op.f("fk_live_proposals_session_id_live_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["live_tables.id"],
            name=op.f("fk_live_proposals_table_id_live_tables"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_live_proposals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("session_id", "position", "user_id", name=op.f("pk_live_proposals")),
    )
    op.create_table(
        "live_questions",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column("budget_s", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_live_questions_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["live_sessions.id"],
            name=op.f("fk_live_questions_session_id_live_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["live_tables.id"],
            name=op.f("fk_live_questions_table_id_live_tables"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("session_id", "position", name=op.f("pk_live_questions")),
    )
    op.add_column("attempts", sa.Column("live_session_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_attempts_live_session_id"), "attempts", ["live_session_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_attempts_live_session_id_live_sessions"),
        "attempts",
        "live_sessions",
        ["live_session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "users",
        sa.Column(
            "subdepartments", postgresql.ARRAY(sa.String(length=8)), server_default="{}", nullable=False
        ),
    )
    # A new answering mode: the old release never writes it, so widening the check is safe mid-deploy.
    op.drop_constraint(op.f("ck_attempts_mode"), "attempts", type_="check")
    op.create_check_constraint(
        op.f("ck_attempts_mode"), "attempts", "mode IN ('practice', 'daily', 'mock', 'live')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM attempts WHERE mode = 'live'")
    op.drop_constraint(op.f("ck_attempts_mode"), "attempts", type_="check")
    op.create_check_constraint(op.f("ck_attempts_mode"), "attempts", "mode IN ('practice', 'daily', 'mock')")
    op.drop_column("users", "subdepartments")
    op.drop_constraint(op.f("fk_attempts_live_session_id_live_sessions"), "attempts", type_="foreignkey")
    op.drop_index(op.f("ix_attempts_live_session_id"), table_name="attempts")
    op.drop_column("attempts", "live_session_id")
    op.drop_table("live_questions")
    op.drop_table("live_proposals")
    op.drop_table("live_players")
    op.drop_table("live_answers")
    op.drop_index(op.f("ix_live_tables_session_id"), table_name="live_tables")
    op.drop_table("live_tables")
    op.drop_index(op.f("ix_live_sessions_host_id"), table_name="live_sessions")
    op.drop_table("live_sessions")
    # ### end Alembic commands ###
