"""quiz documents

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-23 21:14:08.387776

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | Sequence[str] | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("event_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_table(
        "quiz_documents",
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_quiz_documents_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quizzes.id"], name=op.f("fk_quiz_documents_quiz_id_quizzes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("quiz_id", "document_id", name=op.f("pk_quiz_documents")),
    )
    op.create_index(op.f("ix_quiz_documents_document_id"), "quiz_documents", ["document_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_documents_document_id"), table_name="quiz_documents")
    op.drop_table("quiz_documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
