"""xp and levels

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-23 18:04:01.001669

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attempts", sa.Column("xp", sa.Integer(), server_default="0", nullable=False))
    op.add_column("attempts", sa.Column("hint_used", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("questions", sa.Column("difficulty", sa.Integer(), server_default="3", nullable=False))
    op.add_column("users", sa.Column("rank", sa.String(length=24), server_default="mingo", nullable=False))
    op.add_column("users", sa.Column("xp", sa.Integer(), server_default="0", nullable=False))
    op.create_check_constraint(
        op.f("ck_users_rank"),
        "users",
        "rank IN ('mingo', 'member', 'department_head', 'technical_director')",
    )
    # Starting difficulty from the kind of answer and the real quiz's time budget (domain/xp.py);
    # the nightly job refines it from how people do.
    op.execute(
        """
        UPDATE questions SET difficulty = LEAST(5, GREATEST(1,
            CASE answer_kind WHEN 'choice-one' THEN 2 WHEN 'numbers' THEN 4 ELSE 3 END
            + CASE WHEN time_s >= 360 THEN 1 WHEN time_s <= 60 THEN -1 ELSE 0 END))
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_users_rank"), "users", type_="check")
    op.drop_column("users", "xp")
    op.drop_column("users", "rank")
    op.drop_column("questions", "difficulty")
    op.drop_column("attempts", "hint_used")
    op.drop_column("attempts", "xp")
    # ### end Alembic commands ###
