"""mock quiz

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-23 13:07:07.686482

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mock_sessions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("counted", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quizzes.id"], name=op.f("fk_mock_sessions_quiz_id_quizzes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_mock_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mock_sessions")),
    )
    op.create_index(op.f("ix_mock_sessions_user_id"), "mock_sessions", ["user_id"], unique=False)
    op.create_index(
        "uq_mock_sessions_open",
        "mock_sessions",
        ["user_id", "quiz_id"],
        unique=True,
        postgresql_where=sa.text("finished_at IS NULL"),
    )
    op.add_column("attempts", sa.Column("session_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_attempts_session_id"), "attempts", ["session_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_attempts_session_id_mock_sessions"),
        "attempts",
        "mock_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_attempts_session_id_mock_sessions"), "attempts", type_="foreignkey")
    op.drop_index(op.f("ix_attempts_session_id"), table_name="attempts")
    op.drop_column("attempts", "session_id")
    op.drop_index(
        "uq_mock_sessions_open", table_name="mock_sessions", postgresql_where=sa.text("finished_at IS NULL")
    )
    op.drop_index(op.f("ix_mock_sessions_user_id"), table_name="mock_sessions")
    op.drop_table("mock_sessions")
    # ### end Alembic commands ###
