"""review tools

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-23 16:14:48.311305

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_reports_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"], ["users.id"], name=op.f("fk_reports_resolved_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reports_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_question_id"), "reports", ["question_id"], unique=False)
    op.create_index(
        "uq_reports_open",
        "reports",
        ["question_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.add_column(
        "answer_keys", sa.Column("override", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("answer_keys", sa.Column("override_display", sa.Text(), nullable=True))
    op.add_column(
        "questions", sa.Column("images_missing", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("questions", sa.Column("excluded", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("questions", sa.Column("exclusion_note", sa.String(length=200), nullable=True))
    op.add_column(
        "questions", sa.Column("labels_reviewed", sa.Boolean(), server_default="false", nullable=False)
    )
    # Until now `playable` only meant "no image missing".
    op.execute("UPDATE questions SET images_missing = NOT playable")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "labels_reviewed")
    op.drop_column("questions", "exclusion_note")
    op.drop_column("questions", "excluded")
    op.drop_column("questions", "images_missing")
    op.drop_column("answer_keys", "override_display")
    op.drop_column("answer_keys", "override")
    op.drop_index("uq_reports_open", table_name="reports", postgresql_where=sa.text("resolved_at IS NULL"))
    op.drop_index(op.f("ix_reports_question_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
