"""ranked lp: the rank moves to rank points; XP becomes the account level (ADR 0007)

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-24 12:29:08.203051

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0014"
down_revision: str | Sequence[str] | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attempts",
        sa.Column(
            "lp", sa.Numeric(precision=7, scale=2, asdecimal=False), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "rank_points",
            sa.Numeric(precision=8, scale=2, asdecimal=False),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("rank_season", sa.SmallInteger(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("rank_best", sa.SmallInteger(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("combo", sa.SmallInteger(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("miss_streak", sa.SmallInteger(), server_default="0", nullable=False))
    # ### end Alembic commands ###
    # Account XP only goes up: what each person earned, without penalties or the old position floors.
    # Everyone is placed by position (domain/rank.PLACEMENT); rank_season 0 tells the app no reset is due.
    op.execute(
        "UPDATE users SET rank_points = CASE position WHEN 'member' THEN 350 WHEN 'department_head' THEN 550 "
        "WHEN 'technical_director' THEN 1050 ELSE 50 END, rank_best = CASE position WHEN 'member' THEN 3 "
        "WHEN 'department_head' THEN 5 WHEN 'technical_director' THEN 10 ELSE 0 END"
    )
    op.execute("UPDATE attempts SET xp = 0 WHERE xp < 0")
    op.execute(
        "UPDATE users SET xp = coalesce((SELECT sum(xp) FROM attempts WHERE attempts.user_id = users.id), 0)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "miss_streak")
    op.drop_column("users", "combo")
    op.drop_column("users", "rank_best")
    op.drop_column("users", "rank_season")
    op.drop_column("users", "rank_points")
    op.drop_column("attempts", "lp")
    # ### end Alembic commands ###
