"""question bank

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-23 12:36:29.895136

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("short_name", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("fsquiz_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("time_s", sa.Integer(), nullable=True),
        sa.Column("images", postgresql.ARRAY(sa.String(length=64)), server_default="{}", nullable=False),
        sa.Column("area", sa.String(length=16), nullable=False),
        sa.Column("topic", sa.String(length=16), nullable=True),
        sa.Column("answer_kind", sa.String(length=16), nullable=False),
        sa.Column("graded", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("playable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("key_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "answer_kind IN ('choice-one', 'choice-many', 'number', 'numbers', 'range', 'text', 'self')",
            name=op.f("ck_questions_answer_kind"),
        ),
        sa.CheckConstraint(
            "area IN ('mech', 'elec', 'rules', 'unclassified')", name=op.f("ck_questions_area")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("fsquiz_id", name=op.f("uq_questions_fsquiz_id")),
    )
    op.create_index(op.f("ix_questions_area"), "questions", ["area"], unique=False)
    op.create_table(
        "quizzes",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("vehicle_class", sa.String(length=8), nullable=False),
        sa.Column("held_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("information", sa.Text(), nullable=True),
        sa.Column("last_qualifier", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
    )
    op.create_table(
        "answer_keys",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("key", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("display", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_answer_keys_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("question_id", name=op.f("pk_answer_keys")),
    )
    op.create_table(
        "answer_options",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_answer_options_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer_options")),
    )
    op.create_index(op.f("ix_answer_options_question_id"), "answer_options", ["question_id"], unique=False)
    op.create_table(
        "quiz_events",
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_quiz_events_event_id_events"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quizzes.id"], name=op.f("fk_quiz_events_quiz_id_quizzes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("quiz_id", "event_id", name=op.f("pk_quiz_events")),
    )
    op.create_table(
        "quiz_questions",
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_quiz_questions_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quizzes.id"], name=op.f("fk_quiz_questions_quiz_id_quizzes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("quiz_id", "question_id", name=op.f("pk_quiz_questions")),
    )
    op.create_index(op.f("ix_quiz_questions_question_id"), "quiz_questions", ["question_id"], unique=False)
    op.create_table(
        "solutions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("images", postgresql.ARRAY(sa.String(length=64)), server_default="{}", nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_solutions_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_solutions")),
    )
    op.create_index(op.f("ix_solutions_question_id"), "solutions", ["question_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_solutions_question_id"), table_name="solutions")
    op.drop_table("solutions")
    op.drop_index(op.f("ix_quiz_questions_question_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    op.drop_table("quiz_events")
    op.drop_index(op.f("ix_answer_options_question_id"), table_name="answer_options")
    op.drop_table("answer_options")
    op.drop_table("answer_keys")
    op.drop_table("quizzes")
    op.drop_index(op.f("ix_questions_area"), table_name="questions")
    op.drop_table("questions")
    op.drop_table("events")
    # ### end Alembic commands ###
