"""daily question

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-23 12:58:23.869625

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_questions",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("area", sa.String(length=16), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_daily_questions_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("day", "area", name=op.f("pk_daily_questions")),
    )
    op.create_index(op.f("ix_daily_questions_question_id"), "daily_questions", ["question_id"], unique=False)
    op.add_column("attempts", sa.Column("day", sa.Date(), nullable=True))
    op.add_column("attempts", sa.Column("area", sa.String(length=16), nullable=True))
    op.add_column("attempts", sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("attempts", sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("attempts", sa.Column("late", sa.Boolean(), nullable=True))
    op.add_column("attempts", sa.Column("points", sa.Integer(), server_default="0", nullable=False))
    op.create_index(
        "uq_attempts_daily",
        "attempts",
        ["user_id", "day", "area"],
        unique=True,
        postgresql_where=sa.text("mode = 'daily'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_attempts_daily", table_name="attempts", postgresql_where=sa.text("mode = 'daily'"))
    op.drop_column("attempts", "points")
    op.drop_column("attempts", "late")
    op.drop_column("attempts", "submitted_at")
    op.drop_column("attempts", "deadline_at")
    op.drop_column("attempts", "area")
    op.drop_column("attempts", "day")
    op.drop_index(op.f("ix_daily_questions_question_id"), table_name="daily_questions")
    op.drop_table("daily_questions")
    # ### end Alembic commands ###
