"""rested xp and streak freezes

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-24 12:55:52.678754

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0015"
down_revision: str | Sequence[str] | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "streak_freezes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_streak_freezes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "day", name=op.f("pk_streak_freezes")),
    )
    op.add_column("users", sa.Column("rested_xp", sa.Integer(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("rested_on", sa.Date(), nullable=True))
    op.add_column("users", sa.Column("streak_freezes", sa.SmallInteger(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("freeze_earned_on", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "freeze_earned_on")
    op.drop_column("users", "streak_freezes")
    op.drop_column("users", "rested_on")
    op.drop_column("users", "rested_xp")
    op.drop_table("streak_freezes")
    # ### end Alembic commands ###
